//! `wave.lock` mirror (T-915.2 §Data layer) — pure, no egui types.
//!
//! Parses `.ai/tickets/wave.lock` into a LOCAL mirror of xtask's
//! `wave_lock::WaveLock`. The app cannot link xtask (it is the heavy bin — clap,
//! jsonschema, map-engine-core — and a long-running GUI must not freeze a fast-moving
//! rule set into itself), so the struct is redeclared here with `deny_unknown_fields`
//! OFF: a newer lock with extra keys must still render (forward-compat read).
//!
//! The lock is rendered VERBATIM — this module never recomputes packing and never
//! re-derives membership. Drift between the lock and the ticket files is the trust
//! banner's job (T-915.3), not this viewer's.
//!
//! A missing lock is a REFUSAL, never an empty plan: `missing_lock_message` mirrors
//! `xtask/src/wave_lock.rs::missing_lock_error` byte-for-byte. `paths_collide` /
//! `collides` mirror `wave_lock::collides` (the prefix-containment rule) for the
//! owns-collision explainer, unit-tested against the same cases.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::discovery::TICKETS_SUBDIR;

/// Lock file name under `.ai/tickets/`.
pub const LOCK_FILE: &str = "wave.lock";

pub fn lock_path(repo_root: &Path) -> PathBuf {
    repo_root.join(TICKETS_SUBDIR).join(LOCK_FILE)
}

/// Mirror of xtask `LockWave` — no `deny_unknown_fields` (see module docs).
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub struct LockWave {
    pub n: u32,
    pub tickets: Vec<String>,
}

/// Mirror of xtask `WaveLock`. `wave_base` keeps the upstream serde default so
/// pre-T-914 locks (no `wave_base` line) still read.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub struct WaveLock {
    pub version: u32,
    pub max_concurrent: usize,
    #[serde(default)]
    pub wave_base: u32,
    pub pack_last: Vec<String>,
    pub waves: Vec<LockWave>,
    pub owns: BTreeMap<String, Vec<String>>,
    pub depends_on: BTreeMap<String, Vec<String>>,
}

/// Lock load outcome. `Missing` and `Refused` are DISTINCT render states — both are
/// refusals (never empty lanes), but only `Missing` carries the DidNotRun text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockState {
    Loaded(WaveLock),
    /// wave.lock absent — the exact DidNotRun refusal message.
    Missing {
        message: String,
    },
    /// Present but unreadable or unparsable — the VERBATIM error, never paraphrased.
    Refused {
        path: PathBuf,
        error: String,
    },
}

/// Byte-for-byte the `xtask/src/wave_lock.rs::missing_lock_error` text.
pub fn missing_lock_message(path: &Path) -> String {
    format!(
        "{} missing — DidNotRun: run `cargo xtask wave repack`. A missing lock is a refusal, never an empty plan.",
        path.display()
    )
}

pub fn parse_lock(text: &str) -> Result<WaveLock, String> {
    toml::from_str(text).map_err(|e| e.to_string())
}

/// Load `repo_root/.ai/tickets/wave.lock`. Never panics, never invents an empty plan.
pub fn load_lock(repo_root: &Path) -> LockState {
    let path = lock_path(repo_root);
    if !path.is_file() {
        return LockState::Missing {
            message: missing_lock_message(&path),
        };
    }
    match fs::read_to_string(&path) {
        Err(e) => LockState::Refused {
            path,
            error: e.to_string(),
        },
        Ok(text) => match parse_lock(&text) {
            Ok(lock) => LockState::Loaded(lock),
            Err(error) => LockState::Refused { path, error },
        },
    }
}

/// One path pair under the prefix-containment rule: equal, or one prefix-contains the
/// other with a '/' boundary. Mirrors the inner comparison of `wave_lock::collides` —
/// `"a/bc"` does NOT collide with `"a/b"` (no boundary).
pub fn paths_collide(x: &str, y: &str) -> bool {
    x == y
        || x.starts_with(&format!("{}/", y.trim_end_matches('/')))
        || y.starts_with(&format!("{}/", x.trim_end_matches('/')))
}

/// Mirror of `wave_lock::collides`: two owns sets collide when ANY path pair does.
pub fn collides(a: &[String], b: &[String]) -> bool {
    a.iter().any(|x| b.iter().any(|y| paths_collide(x, y)))
}

/// EVERY colliding `(a-side, b-side)` pair — the explainer surface ("why these two
/// can never share a wave"), not just the boolean.
pub fn colliding_pairs(a: &[String], b: &[String]) -> Vec<(String, String)> {
    let mut pairs = Vec::new();
    for x in a {
        for y in b {
            if paths_collide(x, y) {
                pairs.push((x.clone(), y.clone()));
            }
        }
    }
    pairs
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::Scratch;

    const FIXTURE: &str = r#"# auto-generated by cargo xtask wave repack — do not hand-edit
version = 1
max_concurrent = 8
wave_base = 132
pack_last = ["T-290"]
future_root_key = "tolerated"

[[waves]]
n = 0
tickets = ["T-001", "T-002"]

[[waves]]
n = 133
tickets = ["T-146", "T-090.4"]
future_wave_key = 7

[owns]
"T-915.2" = ["apps/ticketboard"]
T-146 = ["apps/website/frontend/src/asset_browser.rs"]

[depends_on]
"T-915.2" = ["T-915.1"]
"#;

    #[test]
    fn parse_fixture_including_wave_base_and_pack_last() {
        let lock = parse_lock(FIXTURE).unwrap();
        assert_eq!(lock.version, 1);
        assert_eq!(lock.max_concurrent, 8);
        assert_eq!(lock.wave_base, 132);
        assert_eq!(lock.pack_last, vec!["T-290".to_string()]);
        assert_eq!(lock.waves.len(), 2);
        assert_eq!(lock.waves[0].n, 0);
        assert_eq!(lock.waves[0].tickets, vec!["T-001", "T-002"]);
        assert_eq!(lock.waves[1].n, 133);
        assert_eq!(lock.waves[1].tickets, vec!["T-146", "T-090.4"]);
        assert_eq!(lock.owns["T-915.2"], vec!["apps/ticketboard".to_string()]);
        assert_eq!(lock.depends_on["T-915.2"], vec!["T-915.1".to_string()]);
    }

    #[test]
    fn wave_base_defaults_to_zero_for_pre_t914_locks() {
        let lock = parse_lock(
            "version = 1\nmax_concurrent = 8\npack_last = []\nwaves = []\n\n[owns]\n\n[depends_on]\n",
        )
        .unwrap();
        assert_eq!(lock.wave_base, 0);
    }

    #[test]
    fn missing_lock_is_the_did_not_run_refusal() {
        let s = Scratch::new("lock-missing");
        let path = lock_path(s.path());
        // The exact DidNotRun text, pinned literally (not via missing_lock_message).
        let expected = format!(
            "{} missing — DidNotRun: run `cargo xtask wave repack`. A missing lock is a refusal, never an empty plan.",
            path.display()
        );
        match load_lock(s.path()) {
            LockState::Missing { message } => assert_eq!(message, expected),
            other => panic!("expected Missing, got {other:?}"),
        }
        assert_eq!(missing_lock_message(&path), expected);
    }

    #[test]
    fn unparsable_lock_refuses_with_verbatim_error() {
        let s = Scratch::new("lock-garbage");
        let dir = s.path().join(TICKETS_SUBDIR);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join(LOCK_FILE), "not = [valid toml").unwrap();
        match load_lock(s.path()) {
            LockState::Refused { path, error } => {
                assert_eq!(path, lock_path(s.path()));
                assert!(!error.is_empty(), "verbatim TOML error expected");
            }
            other => panic!("expected Refused, got {other:?}"),
        }
    }

    #[test]
    fn missing_required_field_refuses() {
        // Valid TOML, invalid lock: no `version`. Fail-closed with the serde error.
        let err = parse_lock("max_concurrent = 8\npack_last = []\nwaves = []\n").unwrap_err();
        assert!(err.contains("version"), "{err}");
    }

    #[test]
    fn collides_mirror_cases() {
        let one = |s: &str| vec![s.to_string()];
        // Equal paths collide.
        assert!(collides(&one("apps/ticketboard"), &one("apps/ticketboard")));
        // Directory prefix with a '/' boundary collides, both directions.
        assert!(collides(
            &one("apps/ticketboard"),
            &one("apps/ticketboard/src")
        ));
        assert!(collides(
            &one("apps/ticketboard/src"),
            &one("apps/ticketboard")
        ));
        // Non-boundary prefix does NOT collide: "a/bc" vs "a/b".
        assert!(!collides(&one("a/bc"), &one("a/b")));
        assert!(!paths_collide("a/bc", "a/b"));
        // Trailing slash is normalized before the boundary check.
        assert!(paths_collide("a/b/", "a/b/c"));
        assert!(paths_collide("a/b/", "a/b"));
        // Disjoint sets do not collide.
        assert!(!collides(&one("apps/a"), &one("apps/b")));
        assert!(!collides(&[], &one("apps/a")));
    }

    #[test]
    fn colliding_pairs_lists_every_pair() {
        let a = vec!["x".to_string(), "x/y".to_string(), "q".to_string()];
        let b = vec!["x/y/z".to_string(), "r".to_string()];
        let pairs = colliding_pairs(&a, &b);
        assert_eq!(
            pairs,
            vec![
                ("x".to_string(), "x/y/z".to_string()),
                ("x/y".to_string(), "x/y/z".to_string()),
            ]
        );
        // The pairs are the explanation of the boolean, never a different rule.
        assert!(collides(&a, &b));
        assert!(colliding_pairs(&a, &[]).is_empty());
    }

    /// Manual smoke against the LIVE repo lock (`cargo test -p ticketboard -- --ignored`):
    /// proves the mirror struct reads the committed wave.lock verbatim, so the Waves
    /// tab's first render cannot hit a surprise refusal. Ignored by default — the
    /// normal test run stays hermetic (scratch dirs only).
    #[test]
    #[ignore = "reads the live repo wave.lock; run explicitly with -- --ignored"]
    fn live_lock_parses_verbatim() {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let Some(root) = crate::discovery::walk_up_for_tickets(&manifest_dir) else {
            panic!("no {TICKETS_SUBDIR}/ above {}", manifest_dir.display());
        };
        match load_lock(&root) {
            LockState::Loaded(lock) => {
                assert!(!lock.waves.is_empty());
                println!(
                    "live lock: version {} wave_base {} max_concurrent {} — {} waves, {} pack_last",
                    lock.version,
                    lock.wave_base,
                    lock.max_concurrent,
                    lock.waves.len(),
                    lock.pack_last.len()
                );
            }
            other => panic!("live wave.lock refused: {other:?}"),
        }
    }
}
