//! Model.

use super::*;

pub const LOCK_VERSION: u32 = 1;

pub(super) const HEADER: &str = "# auto-generated by cargo xtask wave repack — do not hand-edit\n";

pub fn lock_path(root: &Path) -> PathBuf {
    root.join(crate::repository::WAVE_LOCK)
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct LockWave {
    pub n: u32,
    pub tickets: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct WaveLock {
    pub version: u32,
    pub max_concurrent: usize,
    /// The close-marker ledger base open waves continue from (module header
    /// §NUMBERING). Serde-defaulted so lock blobs without it read at historical revisions and
    /// the raw-TOML stubs in `mod_wave_tests` keep parsing; ALWAYS emitted (even 0) by the
    /// deterministic render. Declared between `max_concurrent` and `pack_last` because struct
    /// order IS emit order, and root-level values must precede the `[[waves]]` tables.
    #[serde(default)]
    pub wave_base: u32,
    pub pack_last: Vec<String>,
    pub waves: Vec<LockWave>,
    /// Pending EMPTIED waves (module header §EMPTIED WAVES): open waves of the
    /// previous lock whose every ticket has shipped, frozen as {label, exact ticket set} by
    /// the repack that dissolved them, held until `wave --close` lands each label's marker.
    /// `carry_emptied` is the only producer. Serde-defaulted so lock blobs without it (and
    /// the raw-TOML stubs) keep parsing; SKIPPED from the render when empty — an
    /// `emptied = []` root value after the `[[waves]]` tables would not even be valid TOML,
    /// and the empty case must render byte-identically to a lock without it. Nonempty it
    /// renders as `[[emptied]]` tables between `[[waves]]` and `[owns]`, labels ascending.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub emptied: Vec<LockWave>,
    pub owns: BTreeMap<String, Vec<String>>,
    pub depends_on: BTreeMap<String, Vec<String>>,
}

impl WaveLock {
    pub fn tickets_in_wave(&self, n: u32) -> Vec<String> {
        self.waves
            .iter()
            .find(|w| w.n == n)
            .map(|w| w.tickets.clone())
            .unwrap_or_default()
    }

    pub fn open_ids(&self) -> Vec<String> {
        self.waves
            .iter()
            .filter(|w| w.n > 0)
            .flat_map(|w| w.tickets.iter().cloned())
            .collect()
    }
}

/// The per-ticket facts the compiler needs, from EVERY `.ai/tickets/T-*.toml` — children
/// included. NOT the parents-only registry loader; a dotted child id must be a candidate.
#[derive(Debug, Clone)]
pub struct TicketView {
    pub id: String,
    pub title: String,
    pub work: bool,
    pub status: StatusName,
    pub order: Option<i64>,
    pub executor: Option<String>,
    pub owns: Vec<String>,
    pub depends_on: Vec<String>,
    pub pack_last: bool,
}

impl TicketView {
    /// Can a slice agent take this ticket? Work + live status + claude-code executor
    /// (absent executor defaults to claude-code, as everywhere else in the pipeline).
    pub fn dispatchable(&self) -> bool {
        self.work
            && self.status.is_live()
            && self.executor.as_deref().unwrap_or("claude-code") == "claude-code"
    }

    /// Belongs in wave 0: landed or never agent-actionable. The status list mirrors the old
    /// registry `dispatchable()` refusals (the typed schema has no `blocked`); a non-claude-code
    /// executor is operator work by the D5 gate regardless of status.
    pub fn parked(&self) -> bool {
        matches!(
            self.status,
            StatusName::Shipped | StatusName::Cancelled | StatusName::Deferred
        ) || self
            .executor
            .as_deref()
            .map(|e| e != "claude-code")
            .unwrap_or(false)
    }
}
