//! Role: live operation source for structural regression checks.
//! Position: frontend test support for the mission-core boundary.
//! Signals & state: compile-time source text only.
//! Invariants: include each production shard once and keep domain and adapter sources distinct.

/// Frontend operations adapter source.
pub(crate) const ENTITY: &str = concat!(
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/mod.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/selection.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/layers.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/comments.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/connections.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/layer_drag.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/arming.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/roster.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/vehicles.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/refile.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/placement.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/zone_draw.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/zones.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/triggers.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/markers.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/entity/selection_index.rs"
    )),
    "\n",
);

/// Frontend operations adapter source.
pub(crate) const CONTEXT: &str = concat!(
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/context/mod.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/context/registration.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/context/environment.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/context/attributes.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/editor/state/operations/context/refresh.rs"
    )),
    "\n",
);

/// Mission document operations source.
pub(crate) const DOMAIN_ENTITY: &str = concat!(
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/mod.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/selection.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/identity.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/comments.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/connections.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/roster.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/vehicles.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/markers.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/zones.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/clipboard.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/placement.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../mission-core/src/doc/operations/entity/factions.rs"
    )),
    "\n",
);
