//! The wave lock's data: the on-disk document and the per-ticket facts the compiler reads.
//!
//! **Role:** declares [`WaveLock`] and [`LockWave`] (the serde shape of `.ai/tickets/wave.lock`)
//! and [`TicketView`] (one ticket file reduced to the facts packing needs, with the
//! [`TicketView::dispatchable`] and [`TicketView::parked`] rules).
//! **Position:** the vocabulary every other module of the crate speaks; `ticket_views` builds the
//! views, `compiler` and `persistence` build and write the lock, `verification` reads both.
//! **Signals & state:** none; plain data.
//! **Invariants:** struct field order is TOML emit order, so root values (`version`,
//! `max_concurrent`, `wave_base`, `pack_last`) precede the `[[waves]]` tables, then `[[emptied]]`
//! when nonempty, then the `owns` and `depends_on` tables; unknown keys refuse the parse.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use ticket_model::{StatusName, TicketId};

/// The lock format version this crate writes and accepts; `wave check` reports any other value.
pub const LOCK_VERSION: u32 = 1;

/// The comment line every rendered lock starts with.
pub(super) const HEADER: &str = "# auto-generated by cargo xtask wave repack — do not hand-edit\n";

/// The absolute path of the wave lock under the checkout `root` (`.ai/tickets/wave.lock`).
pub fn lock_path(root: &Path) -> PathBuf {
    root.join(repository_layout::WAVE_LOCK)
}

/// One numbered wave: a `[[waves]]` or `[[emptied]]` table of the lock.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct LockWave {
    /// The wave label (TOML key `n`): 0 for the parked ledger, otherwise a number past the
    /// close-marker ledger base.
    pub n: u32,
    /// The ticket ids of the wave, in packing order; each serialises as its bare string.
    pub tickets: Vec<TicketId>,
}

/// The whole `.ai/tickets/wave.lock` document.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct WaveLock {
    /// The format version; equals [`LOCK_VERSION`] in a lock this crate wrote.
    pub version: u32,
    /// The most tickets one open wave may hold, as the repack that wrote the lock packed it; an
    /// incidental repack keeps this width.
    pub max_concurrent: usize,
    /// The newest standing `wave N CLOSED` number in git history when the lock was packed, 0 when
    /// none is reachable; open waves number past it. Defaults to 0 when the key is absent (locks
    /// read at older revisions) and is always rendered, even as 0. It sits between
    /// `max_concurrent` and `pack_last` because field order is emit order and root values must
    /// precede the `[[waves]]` tables.
    #[serde(default)]
    pub wave_base: u32,
    /// Every ticket with `pack_last = true`, corpus-wide, in ticket id order; each packs into a
    /// single-ticket wave after all others.
    pub pack_last: Vec<TicketId>,
    /// Wave 0 (when it has members) followed by the open waves, labels strictly increasing.
    pub waves: Vec<LockWave>,
    /// Waves pending close (`[[emptied]]`): open waves of an earlier lock whose every ticket has
    /// shipped or been cancelled, frozen as their label and exact ticket set until the matching
    /// `wave N CLOSED` commit lands. Labels ascend and sit between `wave_base` and the first open
    /// wave. Defaults to empty when absent, and is left out of the render when empty, so a lock
    /// without pending closes renders exactly as one written before the key existed (an
    /// `emptied = []` root value after the `[[waves]]` tables would not be valid TOML).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub emptied: Vec<LockWave>,
    /// Every ticket's nonempty `owns` list, corpus-wide, keyed by id.
    pub owns: BTreeMap<TicketId, Vec<String>>,
    /// Every ticket's nonempty `depends_on` list, corpus-wide, keyed by id.
    pub depends_on: BTreeMap<TicketId, Vec<String>>,
}

impl WaveLock {
    /// The tickets of the wave labelled `n`, or an empty list when the lock has no such wave.
    pub fn tickets_in_wave(&self, n: u32) -> Vec<TicketId> {
        self.waves
            .iter()
            .find(|w| w.n == n)
            .map(|w| w.tickets.clone())
            .unwrap_or_default()
    }

    /// Every ticket of the open waves (labels above 0), in lock order.
    pub fn open_ids(&self) -> Vec<TicketId> {
        self.waves
            .iter()
            .filter(|w| w.n > 0)
            .flat_map(|w| w.tickets.iter().cloned())
            .collect()
    }
}

/// The per-ticket facts the compiler needs, read from every `.ai/tickets/T-*.toml`, child
/// tickets included (a dotted child id is a packing candidate like any parent).
#[derive(Debug, Clone)]
pub struct TicketView {
    /// The ticket's id, equal to its file stem.
    pub id: TicketId,
    /// The ticket's title, shown by the collision report.
    pub title: String,
    /// `true` for a work ticket, `false` for a program ticket (which never packs).
    pub work: bool,
    /// The ticket's lifecycle status.
    pub status: StatusName,
    /// The status block's `order`, the first packing sort key; `None` when the status carries
    /// none, which sorts after every ordered ticket.
    pub order: Option<i64>,
    /// The ticket's `executor`; `None` means `claude-code`.
    pub executor: Option<String>,
    /// The repository paths the ticket edits; two tickets collide when a path pair is equal or
    /// one contains the other.
    pub owns: Vec<String>,
    /// The ids of the tickets that must land before this one.
    pub depends_on: Vec<String>,
    /// `true` when the ticket file sets `pack_last = true`.
    pub pack_last: bool,
}

impl TicketView {
    /// Whether a slice agent can take this ticket: a work ticket, a live status (`queued`,
    /// `ready`, `running`, `review`) and the `claude-code` executor, which an absent executor
    /// means.
    pub fn dispatchable(&self) -> bool {
        self.work
            && self.status.is_live()
            && self.executor.as_deref().unwrap_or("claude-code") == "claude-code"
    }

    /// Whether the ticket belongs in wave 0: shipped, cancelled or deferred, or assigned to an
    /// executor other than `claude-code` (operator work whatever its status).
    pub fn parked(&self) -> bool {
        matches!(
            self.status,
            StatusName::Shipped | StatusName::Cancelled | StatusName::Deferred
        ) || self
            .executor
            .as_deref()
            .map(|e| e != "claude-code")
            .unwrap_or(false)
    }
}
