use super::*;
use crate::testutil::Scratch;

const FIXTURE: &str = r#"# auto-generated by cargo xtask wave repack — do not hand-edit
version = 1
max_concurrent = 8
wave_base = 132
pack_last = ["T-290"]
future_root_key = "tolerated"

[[waves]]
n = 0
tickets = ["T-001", "T-002"]

[[waves]]
n = 133
tickets = ["T-146", "T-090.4"]
future_wave_key = 7

[owns]
"T-915.2" = ["apps/ticketboard"]
T-146 = ["apps/website/frontend/src/asset_browser.rs"]

[depends_on]
"T-915.2" = ["T-915.1"]
"#;

#[test]
fn parse_fixture_including_wave_base_and_pack_last() {
    let lock = parse_lock(FIXTURE).unwrap();
    assert_eq!(lock.version, 1);
    assert_eq!(lock.max_concurrent, 8);
    assert_eq!(lock.wave_base, 132);
    assert_eq!(lock.pack_last, vec!["T-290".to_string()]);
    assert_eq!(lock.waves.len(), 2);
    assert_eq!(lock.waves[0].n, 0);
    assert_eq!(lock.waves[0].tickets, vec!["T-001", "T-002"]);
    assert_eq!(lock.waves[1].n, 133);
    assert_eq!(lock.waves[1].tickets, vec!["T-146", "T-090.4"]);
    assert_eq!(lock.owns["T-915.2"], vec!["apps/ticketboard".to_string()]);
    assert_eq!(lock.depends_on["T-915.2"], vec!["T-915.1".to_string()]);
}

#[test]
fn wave_base_defaults_to_zero_for_pre_t914_locks() {
    let lock = parse_lock(
        "version = 1\nmax_concurrent = 8\npack_last = []\nwaves = []\n\n[owns]\n\n[depends_on]\n",
    )
    .unwrap();
    assert_eq!(lock.wave_base, 0);
}

#[test]
fn missing_lock_is_the_did_not_run_refusal() {
    let s = Scratch::new("lock-missing");
    let path = lock_path(s.path());
    // The exact DidNotRun text, pinned literally (not via missing_lock_message).
    let expected = format!(
        "{} missing — DidNotRun: run `cargo xtask wave repack`. A missing lock is a refusal, never an empty plan.",
        path.display()
    );
    match load_lock(s.path()) {
        LockState::Missing { message } => assert_eq!(message, expected),
        other => panic!("expected Missing, got {other:?}"),
    }
    assert_eq!(missing_lock_message(&path), expected);
}

#[test]
fn unparsable_lock_refuses_with_verbatim_error() {
    let s = Scratch::new("lock-garbage");
    let dir = s.path().join(ticket_engine::repository::TICKETS_DIR);
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(lock_path(s.path()), "not = [valid toml").unwrap();
    match load_lock(s.path()) {
        LockState::Refused { path, error } => {
            assert_eq!(path, lock_path(s.path()));
            assert!(!error.is_empty(), "verbatim TOML error expected");
        }
        other => panic!("expected Refused, got {other:?}"),
    }
}

#[test]
fn missing_required_field_refuses() {
    // Valid TOML, invalid lock: no `version`. Fail-closed with the serde error.
    let err = parse_lock("max_concurrent = 8\npack_last = []\nwaves = []\n").unwrap_err();
    assert!(err.contains("version"), "{err}");
}

#[test]
fn collides_mirror_cases() {
    let one = |s: &str| vec![s.to_string()];
    // Equal paths collide.
    assert!(collides(&one("apps/ticketboard"), &one("apps/ticketboard")));
    // Directory prefix with a '/' boundary collides, both directions.
    assert!(collides(
        &one("apps/ticketboard"),
        &one("apps/ticketboard/src")
    ));
    assert!(collides(
        &one("apps/ticketboard/src"),
        &one("apps/ticketboard")
    ));
    // Non-boundary prefix does NOT collide: "a/bc" vs "a/b".
    assert!(!collides(&one("a/bc"), &one("a/b")));
    assert!(!paths_collide("a/bc", "a/b"));
    // Trailing slash is normalized before the boundary check.
    assert!(paths_collide("a/b/", "a/b/c"));
    assert!(paths_collide("a/b/", "a/b"));
    // Disjoint sets do not collide.
    assert!(!collides(&one("apps/a"), &one("apps/b")));
    assert!(!collides(&[], &one("apps/a")));
}

#[test]
fn colliding_pairs_lists_every_pair() {
    let a = vec!["x".to_string(), "x/y".to_string(), "q".to_string()];
    let b = vec!["x/y/z".to_string(), "r".to_string()];
    let pairs = colliding_pairs(&a, &b);
    assert_eq!(
        pairs,
        vec![
            ("x".to_string(), "x/y/z".to_string()),
            ("x/y".to_string(), "x/y/z".to_string()),
        ]
    );
    // The pairs are the explanation of the boolean, never a different rule.
    assert!(collides(&a, &b));
    assert!(colliding_pairs(&a, &[]).is_empty());
}

/// Manual smoke against the LIVE repo lock (`cargo test -p ticketboard -- --ignored`):
/// proves the mirror struct reads the committed wave.lock verbatim, so the Waves
/// tab's first render cannot hit a surprise refusal. Ignored by default — the
/// normal test run stays hermetic (scratch dirs only).
#[test]
#[ignore = "reads the live repo wave.lock; run explicitly with -- --ignored"]
fn live_lock_parses_verbatim() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let Some(root) = crate::discovery::walk_up_for_tickets(&manifest_dir) else {
        panic!(
            "no {}/ above {}",
            ticket_engine::repository::TICKETS_DIR,
            manifest_dir.display()
        );
    };
    match load_lock(&root) {
        LockState::Loaded(lock) => {
            assert!(!lock.waves.is_empty());
            println!(
                "live lock: version {} wave_base {} max_concurrent {} — {} waves, {} pack_last",
                lock.version,
                lock.wave_base,
                lock.max_concurrent,
                lock.waves.len(),
                lock.pack_last.len()
            );
        }
        other => panic!("live wave.lock refused: {other:?}"),
    }
}
