//! T-181.11.2 — the admin audit trail.
//!
//! These are **powers, not conveniences**: under ONE LIFE an admin respawn hands a player back a
//! life the event says they had already spent, and a forced stage change moves the round for
//! everybody. A surface that can do that has to leave a record of who did what to whom, or the
//! only account of a contested call is somebody's memory.
//!
//! ── What is recorded ────────────────────────────────────────────────────────────────────────
//! Every attempt that reaches `TBD_AdminService`, including the ones that were **REFUSED**. A
//! security log that only lists successes cannot answer "did somebody try". Refusals are flagged
//! so the screen can ink them differently and so `TBD_Log.Warn` carries them at WARNING level.
//!
//! ── Where it lives ──────────────────────────────────────────────────────────────────────────
//! SERVER-side and static, so the chat commands (`TBD_AdminCommands`) and the admin screen
//! (`TBD_AdminScreen`, over RPC) share ONE trail rather than each keeping their own. The client
//! never writes to it — it only ever receives a copy inside the snapshot payload.
//!
//! Statics outlive a world inside one process (measured landmine in this codebase). That is
//! deliberate here: an admin who force-switches the mission and restarts the scenario is exactly
//! the event the next round's operator wants to still be able to read.
class TBD_AdminAuditEntry
{
	string m_sTime;   //!< server-local HH:MM:SS at the moment the action was attempted
	string m_sText;   //!< "Hicks(3) respawn Vasquez(7) -> DEPLOYED"
	bool m_bDenied;   //!< the attempt was refused (permission, or the operation said no)

	//! T-181.30 — this entry is an UNAUTHORISED-access refusal: someone who is not on the admin
	//! list touched an admin surface. A strict subset of `m_bDenied`, which also covers an admin
	//! whose legitimate action the operation itself refused.
	//!
	//! The distinction exists because these two have different threat models. An authorised
	//! refusal is generated by someone we trust, at human rates. An unauthorised one is generated
	//! by whoever is attacking the server, at whatever rate they like — so it is the only class of
	//! entry that needs a budget. NOT serialised to clients: the screen still renders from
	//! `m_bDenied`, so this adds no wire-format change.
	bool m_bUnauthorised;

	//------------------------------------------------------------------------------------------------
	void TBD_AdminAuditEntry(string time, string text, bool denied)
	{
		m_sTime = time;
		m_sText = text;
		m_bDenied = denied;
	}
}

//! @authority server — the trail is written on the server only; clients receive a copy.
class TBD_AdminAudit
{
	//! Log channel. A local constant rather than an edit to `TBD_Log`'s vocabulary — two slices
	//! adding a channel to that one enum block in the same wave is a merge conflict for no
	//! benefit, and `TBD_BriefingService.CH_BRIEFING` already set that precedent.
	static const string CH_ADMIN = "Admin";

	//! Bounded on purpose. A long event with a busy admin must not grow an unbounded array that is
	//! then serialised into a reliable-channel RPC every refresh.
	protected static const int MAX_ENTRIES = 60;

	//! How many entries the chat replay (`#tbd audit`) prints. Chat is not a log file.
	protected static const int CHAT_LINES = 12;

	//! T-181.30 — HARD CEILING on how many of the `MAX_ENTRIES` slots unauthorised-access refusals
	//! may hold at once. The remaining `MAX_ENTRIES - MAX_UNAUTHORISED_ENTRIES` (= 48) are
	//! structurally unreachable by an attacker.
	//!
	//! Why a budget and not just de-duplication, which is what this used to rely on: `NoteDeniedAccess`
	//! de-duped per (playerId, surface), which bounds ONE client but not the population. There are
	//! roughly six distinct admin surfaces, so about ten unauthorised clients produce ~60 distinct
	//! pairs — enough to push every real admin action out of a 60-entry ring while each individual
	//! client looks perfectly well-behaved. An audit trail you can flush by attacking it is not an
	//! audit trail, and de-duplication was never going to be the thing that stopped that.
	//!
	//! Set to CHAT_LINES so a full `#tbd audit` page can still be entirely real actions.
	protected static const int MAX_UNAUTHORISED_ENTRIES = 12;

	protected static ref array<ref TBD_AdminAuditEntry> s_aEntries;

	//------------------------------------------------------------------------------------------------
	protected static void Ensure()
	{
		if (!s_aEntries)
			s_aEntries = {};
	}

	//------------------------------------------------------------------------------------------------
	//! Record one admin action attempt. `denied` covers both "not allowed" and "allowed but the
	//! operation refused"; either way the admin tried and the trail says so.
	//! @authority server
	static void Record(string text, bool denied)
	{
		RecordEntry(text, denied, false);
	}

	//------------------------------------------------------------------------------------------------
	//! T-181.30 — record an UNAUTHORISED-access refusal, against its own bounded budget.
	//!
	//! Same ring, same console line, but these entries can only ever occupy
	//! `MAX_UNAUTHORISED_ENTRIES` slots: the oldest one is evicted to make room for a new one, so
	//! they roll among themselves instead of eating into everybody else's. The newest refusals are
	//! the ones kept, which is the useful end — an attack in progress is more actionable than the
	//! first packet of one that has been running for an hour, and the console has the full history
	//! either way.
	//! @authority server
	static void RecordUnauthorised(string text)
	{
		RecordEntry(text, true, true);
	}

	//------------------------------------------------------------------------------------------------
	//! @authority server
	protected static void RecordEntry(string text, bool denied, bool unauthorised)
	{
		Ensure();

		if (unauthorised)
			EvictOldestUnauthorised();

		string time = Timestamp();
		TBD_AdminAuditEntry entry = new TBD_AdminAuditEntry(time, text, denied);
		entry.m_bUnauthorised = unauthorised;
		s_aEntries.Insert(entry);

		// Enfusion arrays remove BY INDEX (TBD_MOD_DESIGN.md §5). Index 0 is the oldest.
		while (s_aEntries.Count() > MAX_ENTRIES)
		{
			s_aEntries.Remove(0);
		}

		// The console is the durable copy — the in-memory ring dies with the process.
		if (denied)
			TBD_Log.Warn(CH_ADMIN, time + " " + text);
		else
			TBD_Log.Event(CH_ADMIN, time + " " + text);
	}

	//------------------------------------------------------------------------------------------------
	//! Drop the oldest unauthorised entries until inserting one more stays within budget.
	//!
	//! A `while`, not an `if`: the loop is what makes the bound hold no matter how the ring got into
	//! its current shape, rather than only when every insert went through this path.
	//! @authority server
	protected static void EvictOldestUnauthorised()
	{
		while (CountUnauthorised() >= MAX_UNAUTHORISED_ENTRIES)
		{
			int oldest = -1;
			for (int i = 0; i < s_aEntries.Count(); i++)
			{
				if (s_aEntries[i].m_bUnauthorised)
				{
					oldest = i;
					break;
				}
			}

			// Nothing to evict. Cannot happen while the count is at budget, but a loop that can
			// only exit by finding something is a hang, so it exits here instead.
			if (oldest == -1)
				return;

			s_aEntries.Remove(oldest);
		}
	}

	//------------------------------------------------------------------------------------------------
	//! @authority server
	protected static int CountUnauthorised()
	{
		int count = 0;
		for (int i = 0; i < s_aEntries.Count(); i++)
		{
			if (s_aEntries[i].m_bUnauthorised)
				count++;
		}

		return count;
	}

	//------------------------------------------------------------------------------------------------
	//! Console-only WARNING, no ring insert.
	//!
	//! For the REPEAT of a refusal whose first occurrence already took a slot. Keeping repeats off
	//! the ring is about SIGNAL — twelve copies of one line tell you nothing the first did not —
	//! and it is no longer what protects the ring from being flushed. `MAX_UNAUTHORISED_ENTRIES`
	//! is: T-181.30 found that de-duplication bounds one client and not the population, which is
	//! the shape the attack actually takes. See that constant.
	//! @authority server
	static void Note(string text)
	{
		TBD_Log.Warn(CH_ADMIN, Timestamp() + " " + text);
	}

	//------------------------------------------------------------------------------------------------
	//! Oldest first. Never null.
	static array<ref TBD_AdminAuditEntry> GetEntries()
	{
		Ensure();
		return s_aEntries;
	}

	//------------------------------------------------------------------------------------------------
	static int GetCount()
	{
		Ensure();
		return s_aEntries.Count();
	}

	//------------------------------------------------------------------------------------------------
	//! `#tbd audit` — the trail in chat, newest first, capped. The fallback surface for an event
	//! running before the menu preset is registered.
	static array<string> BuildReportLines()
	{
		Ensure();

		array<string> lines = new array<string>();

		if (s_aEntries.IsEmpty())
		{
			lines.Insert("TBD audit: no admin actions this session.");
			return lines;
		}

		lines.Insert(string.Format("TBD audit: %1 admin action(s) this session, newest first.", s_aEntries.Count()));

		int shown = 0;
		for (int i = s_aEntries.Count() - 1; i >= 0; i--)
		{
			if (shown >= CHAT_LINES)
			{
				lines.Insert(string.Format("… and %1 older (see the server console for the full trail).", i + 1));
				break;
			}

			TBD_AdminAuditEntry entry = s_aEntries[i];
			string mark = "  ";
			if (entry.m_bDenied)
				mark = "! ";

			lines.Insert(string.Format("%1%2  %3", mark, entry.m_sTime, entry.m_sText));
			shown++;
		}

		return lines;
	}

	//------------------------------------------------------------------------------------------------
	//! Server-local wall clock, `HH:MM:SS`. `System.GetHourMinuteSecond` is a native engine call and
	//! so resolves through no script index — probed against the compiler, which is the only oracle
	//! for a native symbol (SLICE_WORKFLOW.md §Sources).
	//!
	//! `int.ToString(2)` is the width argument; whether it pads with zeros or spaces is a
	//! presentation detail nothing here depends on.
	static string Timestamp()
	{
		int hour;
		int minute;
		int second;
		System.GetHourMinuteSecond(hour, minute, second);

		return string.Format("%1:%2:%3", hour.ToString(2), minute.ToString(2), second.ToString(2));
	}
}
