//! Page signals captured by the browser canvas mount.

use super::*;

/// Page signals captured when the browser canvas mounts.
pub(crate) struct PageMountSignals {
    pub container_ref: NodeRef<leptos::html::Div>,
    pub canvas_ref: NodeRef<leptos::html::Canvas>,
    pub can_undo: RwSignal<bool>,
    pub can_redo: RwSignal<bool>,
    pub obj_count: RwSignal<usize>,
    pub sel_count: RwSignal<usize>,
    pub cursor: RwSignal<Option<(f64, f64, Option<f64>)>>,
    pub debug_hud: RwSignal<String>,
    pub debug_hud_shown: RwSignal<bool>,
    pub scale_mpp: RwSignal<f64>,
    pub tool_mode: RwSignal<website_map_engine::editing::tools::ruler::EditorTool>,
    pub los_mode: RwSignal<LosMode>,
    pub ruler_status: RwSignal<Option<String>>,
    pub ruler_tick: RwSignal<u64>,
    pub los_tick: RwSignal<u64>,
    pub snap: RwSignal<transform::SnapState>,
    pub widget_variant: RwSignal<transform::WidgetVariant>,
    pub boot: RwSignal<BootPhase>,
    pub map_disabled: RwSignal<Option<String>>,
    pub progress: RwSignal<boot_progress::BootProgress>,
    pub outliner_nodes:
        RwSignal<Vec<crate::v2::apps::editor::ui::outliner::outliner::OutlinerNode>>,
    pub orbat_nodes: RwSignal<Vec<crate::v2::apps::editor::ui::outliner::outliner::OutlinerNode>>,
    pub selected_ids: RwSignal<Vec<String>>,
    pub active_layer: RwSignal<Option<String>>,
    pub active_side: RwSignal<String>,
    pub objects_mode: RwSignal<bool>,
    pub catalog: RwSignal<crate::v2::apps::editor::arsenal::asset_catalog::CatalogState>,
    pub vehicle_catalog: RwSignal<crate::v2::apps::editor::arsenal::asset_catalog::CatalogState>,
    pub attrs_open: RwSignal<Option<String>>,
    pub attrs_tab: RwSignal<usize>,
    pub doc_tick: RwSignal<u64>,
    pub selected_connection: RwSignal<Option<String>>,
    pub context_menu: RwSignal<Option<crate::v2::apps::editor::ui::docks::context_menu::MenuState>>,
    pub asset_picker: RwSignal<Option<AssetPickerState>>,
    pub comment_editor: RwSignal<Option<String>>,
    pub connections_panel: RwSignal<bool>,
    pub chrome_hidden: RwSignal<bool>,
    pub dock_left_collapsed: RwSignal<bool>,
    pub dock_right_collapsed: RwSignal<bool>,
    pub registry_items: RwSignal<Option<Vec<crate::v2::core::api::dto::RegistryItem>>>,
    pub registry_failed: RwSignal<bool>,
    pub registry_fetch_gen: RwSignal<u64>,
    pub compat: RwSignal<crate::v2::apps::editor::arsenal::rules::CompatFeed>,
    pub dirty: RwSignal<bool>,
    pub conflict: RwSignal<Option<ConflictInfo>>,
    pub current_semver: RwSignal<Option<String>>,
    pub mission_id: String,
}
