// Contract codegen (DOCUMENTATION_STANDARDS §9.1). Generates the TypeScript and Rust
// projections of the shared JSON schemas so cross-boundary types are GENERATED, not
// hand-copied. Tools (one Node toolchain): TypeScript via `json-schema-to-typescript`
// (preserves exact wire field names); Rust via `quicktype` (serde structs). The Rust
// validator + kit-aliases reach the canonical schemas directly via include_str!, so no
// schema-copy step is needed. (Go projection removed at the T-145 cutover.)
//
// Run via `make schema-codegen`. Generated outputs are marked DO NOT EDIT.
import { compileFromFile } from "json-schema-to-typescript";
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(root, "..", "..");
const schemaDir = join(root, "schema");
const tsOut = join(repoRoot, "apps", "website", "frontend", "src", "types", "contract");
// T-145: serde projections live alongside the crate source.
const rustRoot = join(repoRoot, "apps", "website", "src", "contract", "generated");

// Schemas with a cross-boundary TS + Rust projection.
const targets = [
  { schema: "registry-items.schema.json", ts: "registryItems.ts", rust: "registry_items" },
  { schema: "registry-compat.schema.json", ts: "registryCompat.ts", rust: "registry_compat" },
  { schema: "loadout-export.schema.json", ts: "loadoutExport.ts", rust: "loadout" },
  { schema: "mission-editor-payload.schema.json", ts: "missionEditorPayload.ts", rust: "mission_editor" },
];

const tsBanner = (s) => `/* eslint-disable */
/**
 * @generated by packages/tbd-schema/scripts/codegen.mjs — DO NOT EDIT BY HAND.
 * Regenerate: make schema-codegen
 * Source: packages/tbd-schema/schema/${s}
 */`;

mkdirSync(tsOut, { recursive: true });
mkdirSync(rustRoot, { recursive: true });

for (const t of targets) {
  const schemaPath = join(schemaDir, t.schema);

  // TypeScript — json-schema-to-typescript preserves snake_case/camelCase field names verbatim.
  const ts = await compileFromFile(schemaPath, {
    bannerComment: tsBanner(t.schema),
    additionalProperties: true,
    declareExternallyReferenced: true,
    style: { singleQuote: true, semi: false },
  });
  writeFileSync(join(tsOut, t.ts), ts);

  // Rust — quicktype serde structs. include_str! reaches the canonical schemas directly,
  // so no schema copy step is needed on the Rust side.
  const rustFile = join(rustRoot, `${t.rust}.rs`);
  execFileSync(
    "npx",
    ["quicktype", "-s", "schema", schemaPath, "-l", "rust", "--visibility", "public", "--derive-debug", "-o", rustFile],
    { stdio: "inherit", cwd: root },
  );
  const banner = `// Code generated from JSON Schema using quicktype. DO NOT EDIT.\n// Source: packages/tbd-schema/schema/${t.schema} — regenerate with: make schema-codegen\n\n`;
  writeFileSync(rustFile, banner + readFileSync(rustFile, "utf8"));
  // Format so the committed output is rustfmt-stable (keeps codegen-drift + `cargo fmt
  // --check` both green). rustfmt is on PATH via the rust toolchain.
  execFileSync("rustfmt", ["--edition", "2024", rustFile], { stdio: "inherit" });

  console.log(`  ${t.schema} -> types/contract/${t.ts} + src/contract/generated/${t.rust}.rs`);
}

// Registry data the flatten implementation consumes (T-092.2): canonical copy lives in
// packages/tbd-schema/registry/; the Rust side include_str!s it directly, so only the
// Vite JSON import copy is mirrored here.
const registryAssets = ["kit-aliases.json"];
const registrySrc = join(root, "registry");
for (const f of registryAssets) {
  copyFileSync(join(registrySrc, f), join(tsOut, f));
  console.log(`  registry: types/contract/${f}`);
}

console.log("schema-codegen complete");
