// Contract codegen (DOCUMENTATION_STANDARDS §9.1). Generates the Go and TypeScript
// projections of the shared JSON schemas so cross-boundary types are GENERATED, not
// hand-copied. Tools (one Node toolchain): TypeScript via `json-schema-to-typescript`
// (preserves exact wire field names); Go via `quicktype` (emits idiomatic structs with
// correct `json:"..."` tags). It also copies the schemas the Go validator embeds into the
// module tree, because go:embed cannot reach files outside apps/website/.
//
// Run via `make schema-codegen`. Generated outputs are marked DO NOT EDIT.
import { compileFromFile } from "json-schema-to-typescript";
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(root, "..", "..");
const schemaDir = join(root, "schema");
const tsOut = join(repoRoot, "apps", "website", "frontend", "src", "types", "contract");
const goRoot = join(repoRoot, "apps", "website", "internal", "contract");

// Schemas with a cross-boundary Go + TS projection.
const targets = [
  { schema: "registry-items.schema.json", ts: "registryItems.ts", goPkg: "registryitems" },
  { schema: "loadout-export.schema.json", ts: "loadoutExport.ts", goPkg: "loadout" },
  { schema: "mission-editor-payload.schema.json", ts: "missionEditorPayload.ts", goPkg: "missioneditor" },
];

// Schemas copied into the Go module so internal/contract can go:embed them for runtime validation.
const embedSchemas = ["mission-editor-payload.schema.json", "mission.schema.json"];

const tsBanner = (s) => `/* eslint-disable */
/**
 * @generated by packages/tbd-schema/scripts/codegen.mjs — DO NOT EDIT BY HAND.
 * Regenerate: make schema-codegen
 * Source: packages/tbd-schema/schema/${s}
 */`;

mkdirSync(tsOut, { recursive: true });
mkdirSync(goRoot, { recursive: true });

for (const t of targets) {
  const schemaPath = join(schemaDir, t.schema);

  // TypeScript — json-schema-to-typescript preserves snake_case/camelCase field names verbatim.
  const ts = await compileFromFile(schemaPath, {
    bannerComment: tsBanner(t.schema),
    additionalProperties: true,
    declareExternallyReferenced: true,
    style: { singleQuote: true, semi: false },
  });
  writeFileSync(join(tsOut, t.ts), ts);

  // Go — quicktype emits structs with correct json tags + a "DO NOT EDIT" banner.
  const pkgDir = join(goRoot, t.goPkg);
  mkdirSync(pkgDir, { recursive: true });
  const goFile = join(pkgDir, `${t.goPkg}.gen.go`);
  execFileSync(
    "npx",
    ["quicktype", "-s", "schema", schemaPath, "-l", "go", "--package", t.goPkg, "-o", goFile],
    { stdio: "inherit", cwd: root },
  );
  const src = readFileSync(goFile, "utf8");
  writeFileSync(
    goFile,
    src.replace(
      "// Code generated from JSON Schema using quicktype. DO NOT EDIT.",
      `// Code generated from JSON Schema using quicktype. DO NOT EDIT.\n// Source: packages/tbd-schema/schema/${t.schema} — regenerate with: make schema-codegen`,
    ),
  );
  console.log(`  ${t.schema} -> types/contract/${t.ts} + internal/contract/${t.goPkg}/`);
}

// Mirror the validator's schemas into the Go module tree for go:embed.
const embedDir = join(goRoot, "schema");
mkdirSync(embedDir, { recursive: true });
for (const s of embedSchemas) {
  copyFileSync(join(schemaDir, s), join(embedDir, s));
  console.log(`  embed: internal/contract/schema/${s}`);
}

// Registry data both flatten implementations consume (T-092.2): canonical copy lives in
// packages/tbd-schema/registry/; mirrored for go:embed and for the Vite JSON import.
const registryAssets = ["kit-aliases.json"];
const registrySrc = join(root, "registry");
const goRegistryDir = join(goRoot, "registry");
mkdirSync(goRegistryDir, { recursive: true });
for (const f of registryAssets) {
  copyFileSync(join(registrySrc, f), join(goRegistryDir, f));
  copyFileSync(join(registrySrc, f), join(tsOut, f));
  console.log(`  registry: internal/contract/registry/${f} + types/contract/${f}`);
}

console.log("schema-codegen complete");
