//! The fixed strings and value sets the checks and the sync share.
//!
//! **Role:** the generated-file header, the retired-identifier pattern, the roadmap markers and
//! the legal target, executor and stream values of an untyped row.
//! **Position:** read by `crate::validation` and `crate::sync`.
//! **Signals & state:** none; constants.
//! **Invariants:** the marker strings match the ones committed in the roadmap.

/// The header line `queue.json`'s `_comment` carries, naming the command that writes it.
pub const AUTO_HEADER: &str =
    "<!-- AUTO-GENERATED by cargo run -q -p xtask -- ticket sync — DO NOT EDIT -->\n\n";

/// The regular expression of retired planning identifiers (priority codes, backlog and track
/// ids) that `ticket check --strict` reports in documents. En-dashes U+2013 in `P0–P2` and
/// `P0–P3`: the documents spell them that way.
pub const STRICT_LEGACY: &str = concat!(
    r"\bP[0-3]-[0-9]{2}\b|\bP[0-3]-0[0-9]\b",
    r"|Eden P[0-3]|Eden P0|P0–P2|P0-P3|P0–P3",
    r"|\bP0 registry\b|\bP1 feel\b",
    r"|\bFD-0[0-9]{1,2}\b|\bFD-0xx\b|\bFD backlog\b",
    r"|\bBE-0[0-9]{1,2}\b|\bBE-0xx\b|\bBE backlog\b",
    r"|Track [ABC]\b|Tracks [ABC]-[ABC]-[ABC]|Tracks [ABC]-[ABC]",
    r"|\bA-0[0-9]\b|\bB-0[0-9]\b|\bC-0[0-9]\b",
    r#"|\"gap\":\s*\"P[0-3]-"#,
);

/// The roadmap comment that opens the recommended-next-work block `ticket sync` writes.
pub const NEXT_MARKER_START: &str = "<!-- ticket-sync:next:start -->";
/// The roadmap comment that closes the recommended-next-work block.
pub const NEXT_MARKER_END: &str = "<!-- ticket-sync:next:end -->";

/// The legal `targets` values: the four sparse-checkout target sets.
pub const VALID_TARGETS: &[&str] = &["website", "mod", "shared", "root"];
/// The legal `executor` values: who runs a ticket.
pub const VALID_EXECUTORS: &[&str] = &["claude-code", "documentation", "workbench", "human", "ci"];
/// The legal `stream` values of an untyped row: the work streams.
pub const VALID_STREAMS: &[&str] = &[
    "mission-creator",
    "web-platform",
    "mod-framework",
    "shared-schema",
    "content",
    "infra",
    "voip-partner",
];
