//! T-151 camera parity gates against the committed deck.gl 9.3.5 golden fixture
//! (`fixtures/deckgl_ortho_goldens.json`, generated by
//! `apps/website/frontend/scripts/gen-deckgl-ortho-goldens.mjs` — 300 enumerated cases).
//!
//! Gate structure (plan §S3b):
//! - **T1** integer-zoom cases: ULP distance == 0 (bit-exact) on every matrix entry, every
//!   project/unproject output, and bounds. Forced: `2^int` is exact in both `Math.pow` and
//!   `exp2`; every other op follows an identical expression tree (`camera::glmat4`).
//! - **T2** scale-drift isolation (ALL cases): `ulp(exp2(zoom), fixture.scale) ≤ 1` — the
//!   only operation that is not expression-tree-mirrored, measured alone.
//! - **T3** scale-injection exactness (ALL cases, incl. fractional): rebuild the camera with
//!   the oracle's own `scale` → ULP == 0 everywhere. T2+T3 prove the entire pipeline
//!   bit-exact; residual fractional uncertainty is confined to one measured ≤1-ULP scalar.
//! - **T4** end-to-end fractional bound (ALL cases, shipping path): ULP ≤ 2 on matrix
//!   entries, ≤ 4 on projections — T2's scalar propagated through one product
//!   (matrix entry = scale-derived factor × exact factor) plus one transform/divide chain.
//!
//! Plus a fixture-independent closed-form anchor test (hand-derived literals).

use map_engine_core::camera::OrthoCamera;
use serde_json::Value;

// -- ULP metric (port of features/_wasm/parity.ts:62-75 ulpDistanceF64) ---------------------

/// ULP distance between two f64s. `+0`/`-0` → 0; any NaN → `u64::MAX`. i128 intermediate —
/// the JS uses BigInt64 with the same total-order flip across the sign boundary.
fn ulp_distance(a: f64, b: f64) -> u64 {
    #[allow(clippy::float_cmp)] // exact compare is the point: ±0 and identical bits → 0
    if a == b {
        return 0;
    }
    if a.is_nan() || b.is_nan() {
        return u64::MAX;
    }
    fn flip(bits: i64) -> i128 {
        let x = i128::from(bits);
        if x < 0 { i128::from(i64::MIN) - x } else { x }
    }
    let fa = flip(a.to_bits() as i64);
    let fb = flip(b.to_bits() as i64);
    (fa - fb).unsigned_abs().try_into().unwrap_or(u64::MAX)
}

// -- fixture access helpers ------------------------------------------------------------------

fn fixture() -> Value {
    serde_json::from_str(include_str!("fixtures/deckgl_ortho_goldens.json"))
        .expect("golden fixture parses")
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("number")
}

fn floats(v: &Value) -> Vec<f64> {
    v.as_array().expect("array").iter().map(f).collect()
}

struct Case {
    id: String,
    width: f64,
    height: f64,
    zoom: f64,
    target: [f64; 2],
    scale: f64,
}

fn parse_case(v: &Value) -> Case {
    let t = floats(&v["target"]);
    Case {
        id: v["id"].as_str().expect("id").to_owned(),
        width: f(&v["width"]),
        height: f(&v["height"]),
        zoom: f(&v["zoom"]),
        target: [t[0], t[1]],
        scale: f(&v["scale"]),
    }
}

fn camera_own_scale(c: &Case) -> OrthoCamera {
    OrthoCamera::new(c.width, c.height, c.target[0], c.target[1], c.zoom)
}

fn camera_injected_scale(c: &Case) -> OrthoCamera {
    OrthoCamera::with_scale_for_test(c.width, c.height, c.target[0], c.target[1], c.zoom, c.scale)
}

/// Assert every element of `got` is within `max_ulp` of `expected`, with case diagnostics.
fn assert_ulp_slice(got: &[f64], expected: &[f64], max_ulp: u64, what: &str, id: &str) {
    assert_eq!(got.len(), expected.len(), "{id}: {what} length");
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        let d = ulp_distance(*g, *e);
        assert!(
            d <= max_ulp,
            "{id}: {what}[{i}] ULP {d} > {max_ulp} (got {g:e}, expected {e:e})"
        );
    }
}

/// Run every fixture comparison for one case at one ULP budget pair.
fn check_case(v: &Value, cam: &OrthoCamera, matrix_ulp: u64, projection_ulp: u64, id: &str) {
    // Matrices (present only on the 800×600 subset).
    if let Some(vm) = v.get("viewMatrix") {
        assert_ulp_slice(
            &cam.view_matrix(),
            &floats(vm),
            matrix_ulp,
            "viewMatrix",
            id,
        );
        assert_ulp_slice(
            &cam.projection_matrix(),
            &floats(&v["projectionMatrix"]),
            matrix_ulp,
            "projectionMatrix",
            id,
        );
        assert_ulp_slice(
            &cam.view_projection(),
            &floats(&v["viewProjectionMatrix"]),
            matrix_ulp,
            "viewProjectionMatrix",
            id,
        );
        assert_ulp_slice(
            &cam.pixel_projection(),
            &floats(&v["pixelProjectionMatrix"]),
            matrix_ulp,
            "pixelProjectionMatrix",
            id,
        );
        assert_ulp_slice(
            &cam.pixel_unprojection().expect("invertible"),
            &floats(&v["pixelUnprojectionMatrix"]),
            matrix_ulp,
            "pixelUnprojectionMatrix",
            id,
        );
    }

    // World→pixel probes + their round trips.
    for (i, probe) in v["probes"].as_array().expect("probes").iter().enumerate() {
        let world = floats(&probe["world"]);
        let projected = cam.project([world[0], world[1], world[2]]);
        assert_ulp_slice(
            &projected,
            &floats(&probe["project"]),
            projection_ulp,
            &format!("probes[{i}].project"),
            id,
        );
        let rt = cam.unproject_xy(projected[0], projected[1]);
        assert_ulp_slice(
            &rt,
            &floats(&probe["roundTrip"]),
            projection_ulp,
            &format!("probes[{i}].roundTrip"),
            id,
        );
    }

    // Pixel→world unprojects.
    for (i, u) in v["unprojects"]
        .as_array()
        .expect("unprojects")
        .iter()
        .enumerate()
    {
        let pixel = floats(&u["pixel"]);
        let world = cam.unproject_xy(pixel[0], pixel[1]);
        assert_ulp_slice(
            &world,
            &floats(&u["world"]),
            projection_ulp,
            &format!("unprojects[{i}]"),
            id,
        );
    }

    // getBounds mirror.
    assert_ulp_slice(
        &cam.visible_world_rect(),
        &floats(&v["bounds"]),
        projection_ulp,
        "bounds",
        id,
    );
}

// -- Gates -----------------------------------------------------------------------------------

/// T1: integer-zoom cases are bit-exact end to end (ULP == 0 on everything).
#[test]
fn t1_integer_zoom_cases_bit_exact() {
    let fx = fixture();
    let mut checked = 0;
    for v in fx["cases"].as_array().expect("cases") {
        let c = parse_case(v);
        if c.zoom.fract() != 0.0 {
            continue;
        }
        check_case(v, &camera_own_scale(&c), 0, 0, &c.id);
        checked += 1;
    }
    assert_eq!(checked, 180, "6 integer zooms × 6 sizes × 5 targets");
}

/// T2: the pow drift — `exp2(zoom)` vs the oracle's `Math.pow(2, zoom)` — is ≤ 1 ULP,
/// measured in isolation for every case.
#[test]
fn t2_scale_drift_at_most_one_ulp() {
    let fx = fixture();
    for v in fx["cases"].as_array().expect("cases") {
        let c = parse_case(v);
        let d = ulp_distance(c.zoom.exp2(), c.scale);
        assert!(d <= 1, "{}: scale ULP {d} > 1", c.id);
    }
}

/// T3: with the oracle's own scale injected, the ENTIRE pipeline is bit-exact for ALL 300
/// cases — fractional zooms included. This is the primary exactness gate.
#[test]
fn t3_scale_injected_pipeline_bit_exact_all_cases() {
    let fx = fixture();
    let cases = fx["cases"].as_array().expect("cases");
    assert_eq!(cases.len(), 300);
    for v in cases {
        let c = parse_case(v);
        check_case(v, &camera_injected_scale(&c), 0, 0, &c.id);
    }
}

/// T4: the shipping path (own `exp2`) across ALL cases stays within the derived propagation
/// bound: ≤ 2 ULP on matrix entries (one product touched by the ≤1-ULP scale), ≤ 4 ULP on
/// projected outputs (one further transform + divide chain).
#[test]
fn t4_end_to_end_bound_all_cases() {
    let fx = fixture();
    for v in fx["cases"].as_array().expect("cases") {
        let c = parse_case(v);
        check_case(v, &camera_own_scale(&c), 2, 4, &c.id);
    }
}

/// Fixture-independent closed-form anchor (plan §Ground truth): w=800, h=600, zoom=0 (s=1),
/// target=(6400,6400). Every literal below is hand-derived on paper from the deck
/// composition; no oracle involved.
#[test]
fn closed_form_anchor_case() {
    let cam = OrthoCamera::new(800.0, 600.0, 6400.0, 6400.0, 0.0);

    // V = lookAt(eye=[0,0,1]) (= I with m14 = −1), scaled by s=1, translated by −target.
    let v = cam.view_matrix();
    let expected_v: [f64; 16] = [
        1.0, 0.0, 0.0, 0.0, //
        0.0, 1.0, 0.0, 0.0, //
        0.0, 0.0, 1.0, 0.0, //
        -6400.0, -6400.0, -1.0, 1.0,
    ];
    assert_eq!(v, expected_v);

    // P = orthoNO(−400, 400, −300, 300, 0.1, 1000) — first-principles expression mirrors.
    let p = cam.projection_matrix();
    let lr = 1.0 / (-400.0 - 400.0);
    let bt = 1.0 / (-300.0 - 300.0);
    let nf = 1.0 / (0.1 - 1000.0);
    assert_eq!(p[0], -2.0 * lr);
    assert_eq!(p[5], -2.0 * bt);
    assert_eq!(p[10], 2.0 * nf);
    assert_eq!(p[12], 0.0);
    assert_eq!(p[13], 0.0);
    assert_eq!(p[14], (1000.0 + 0.1) * nf);
    assert_eq!(p[15], 1.0);

    // VP translation column: m12 = P[0]·(−6400) — rounds to exactly −16 (within half-ULP).
    assert_eq!(cam.view_projection()[12], -16.0);

    // Screen center: x lands exactly on 400; y within 1e-9 px of 300 (matrix-path
    // cancellation is not exact in floating point — see the fixture's 300.0000000000009).
    let center = cam.project([6400.0, 6400.0, 0.0]);
    assert_eq!(center[0], 400.0);
    assert!((center[1] - 300.0).abs() <= 1e-9);

    // +100 m east ⇒ +100 px right at zoom 0.
    let east = cam.project([6500.0, 6400.0, 0.0]);
    assert!((east[0] - 500.0).abs() <= 1e-9);
    assert!((east[1] - 300.0).abs() <= 1e-9);

    // +100 m north ⇒ 100 px UP — the numeric flipY:false / north-up proof.
    let north = cam.project([6400.0, 6500.0, 0.0]);
    assert!((north[0] - 400.0).abs() <= 1e-9);
    assert!((north[1] - 200.0).abs() <= 1e-9);
}
