/* eslint-disable */
/**
 * @generated by packages/tbd-schema/scripts/codegen.mjs — DO NOT EDIT BY HAND.
 * Regenerate: make schema-codegen
 * Source: packages/tbd-schema/schema/faction-library.schema.json
 */

/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z][a-zA-Z0-9_]{0,63}$".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z][a-zA-Z0-9_]{0,63}$".
 */
export type Slot = string | null
/**
 * Full Enfusion ResourceName ({GUID}Prefabs/.../File.et).
 */
export type ResourceName = string

/**
 * One operator-authored reusable faction (T-153): a side + display name plus its ORBAT role templates (each wrapping a registry character with an optional SlotLoadout v2) and its vehicle pool. Stored as the jsonb doc of a user_factions row; the Mission Creator palette renders side → faction → roles/vehicles from these instead of the raw vanilla registry dump. Role loadouts reuse the loadout-export v2 shapes (wear open map keyed by engine LoadoutSlotInfo name; slot-indexed weapons).
 */
export interface TBDFactionLibraryEntry {
  /**
   * Export-side key (mirrors the mission doc Faction.key vocabulary).
   */
  side: 'BLUFOR' | 'OPFOR' | 'INDFOR' | 'CIV'
  /**
   * Display name, e.g. 'US Army 1980s'.
   */
  name: string
  /**
   * Optional emblem asset path/URL (UI later).
   */
  emblem?: string
  /**
   * ORBAT role templates in authored order — the palette's draggable leaves.
   */
  roles: Role[]
  /**
   * Vehicle pool (listed in the palette; map placement lands with T-070).
   */
  vehicles: Vehicle[]
}
export interface Role {
  role: string
  tag?: string
  /**
   * Registry character (kind === character) this role wraps — vanilla bodies are fine here; the palette hides them, roles don't.
   */
  character: string
  loadout?: LoadoutV2
}
/**
 * SlotLoadout v2 (mirrors loadout-export.schema.json v2 doc shapes).
 */
export interface LoadoutV2 {
  /**
   * SlotLoadout v2 marker (const 2 — expressed as bounds for the quicktype Rust emitter).
   */
  version: number
  wear: {
    [k: string]: Slot
  }
  weapons: {
    slotIndex: number
    slotType: string
    weapon: string
    optic?: Slot
    magazine?: Slot
    attachments?: string[]
  }[]
  equipment?: {
    [k: string]: Slot
  }
  cargo?: {
    container: string
    item: string
    qty: number
  }[]
  summary?: string
}
export interface Vehicle {
  vehicle: ResourceName
  label?: string
}
