/* eslint-disable */
/**
 * @generated by packages/tbd-schema/scripts/codegen.mjs — DO NOT EDIT BY HAND.
 * Regenerate: make schema-codegen
 * Source: packages/tbd-schema/schema/loadout-export.schema.json
 */

/**
 * Enfusion ResourceName for the equipped item, or null when the slot is empty.
 */
export type Slot = string | null

/**
 * Loadout download: a fixed set of gear slots, each holding a resource_name (from registry-items) or null when empty. Consumed by the mod equip test and the web download. optic/magazine are optional Smart Forge slots (T-068.10) — absent in Phase 1 payloads, ignored by the v1 mod reader.
 */
export interface TBDLoadoutExport {
  loadoutVersion: '1'
  modpackId: string
  gear: {
    primary: Slot
    uniform: Slot
    vest: Slot
    helmet: Slot
    optic?: Slot
    magazine?: Slot
  }
}
