/* eslint-disable */
/**
 * @generated by packages/tbd-schema/scripts/codegen.mjs — DO NOT EDIT BY HAND.
 * Regenerate: make schema-codegen
 * Source: packages/tbd-schema/schema/mission-editor-payload.schema.json
 */

/**
 * The 2D-editor 'superset' stored verbatim as a MissionVersion.json_payload (the write side of POST /api/v1/missions/:id/versions; mirrors the frontend compile.ts MissionPayload). This is NOT the canonical mission.schema.json document — that is the game-server contract derived/exported separately. Its integer schemaVersion is the editor-payload format version, a DISTINCT namespace from the canonical mission contract's string schemaVersion. Validation is intentionally lenient on presence (minimal and partial saves are valid, including the empty {} a freshly created mission stores) but strict on type, to reject malformed payloads and the schemaVersion namespace confusion (a string here) before persist.
 */
export interface TBDMissionEditorPayload {
  /**
   * Editor-payload format version (integer; do not confuse with the canonical mission schemaVersion, which is a string).
   */
  schemaVersion?: number
  map?: {
    terrain?: string
    bounds?: number[]
    [k: string]: unknown
  }
  environment?: {
    [k: string]: unknown
  }
  /**
   * Optional backend ORBAT contract (omitted on Save Version; the server derives it from editor).
   */
  orbat?: unknown[]
  loadouts?: {
    [k: string]: unknown
  }
  objectives?: unknown[]
  vehicles?: unknown[]
  markers?: unknown[]
  /**
   * Lossless editor graph. The arrays are intentionally unconstrained (no per-item schema) so validation stays O(1) on missions with hundreds of thousands of slots.
   */
  editor?: {
    factions?: unknown[]
    squads?: unknown[]
    slots?: unknown[]
    editorLayers?: unknown[]
    [k: string]: unknown
  }
  [k: string]: unknown
}
