/* eslint-disable */
/**
 * @generated by packages/tbd-schema/scripts/codegen.mjs — DO NOT EDIT BY HAND.
 * Regenerate: make schema-codegen
 * Source: packages/tbd-schema/schema/registry-compat.schema.json
 */

/**
 * Enfusion ResourceName ({GUID}Prefabs/.../File.et).
 */
export type ResourceName = string

/**
 * Engine-derived compatibility edge graph between registry items (T-150). Nodes are full Enfusion ResourceNames and must exist in the paired registry-items envelope; edges are read from prefab container data (magazine wells, attachment slot types, vehicle weapon slots, character loadout slots) — never hand-authored. Drives canEquip/canAttach (T-068.9 ingest, T-068.10 smart Forge).
 */
export interface TBDRegistryCompat {
  registryCompatVersion: string
  modpackId: string
  generatedAt?: string
  /**
   * Workbench addons loaded during the export (the scan set).
   */
  addons?: Addon[]
  /**
   * @minItems 1
   */
  edges: [Edge, ...Edge[]]
}
export interface Addon {
  /**
   * Addon GUID from GameProject.GetLoadedAddons.
   */
  guid: string
  /**
   * Addon ID (GameProject.GetAddonID), e.g. ArmaReforger.
   */
  name: string
  /**
   * Human title (GameProject.GetAddonTitle).
   */
  title?: string
  /**
   * GameProject.IsVanillaAddon.
   */
  vanilla?: boolean
}
/**
 * Directed compatibility edge. from_node = the item that goes in/on (magazine, ammo, optic, attachment, gear); to_node = the host that accepts it (weapon, magazine, vehicle weapon, character). Per edge_type: mag_in_weapon mag->weapon; ammo_in_mag ammo->magazine; optic_on_weapon optic->weapon; attachment_on_weapon attachment->weapon; mag_in_vehicle_weapon mag->vehicle weapon prefab; ammo_in_vehicle_weapon ammo->vehicle weapon prefab; character_default_loadout gear item->character.
 */
export interface Edge {
  from_node: ResourceName
  to_node: ResourceName
  edge_type:
    | 'mag_in_weapon'
    | 'ammo_in_mag'
    | 'optic_on_weapon'
    | 'attachment_on_weapon'
    | 'mag_in_vehicle_weapon'
    | 'ammo_in_vehicle_weapon'
    | 'character_default_loadout'
  /**
   * Engine class or container var that proved the edge, e.g. MagazineWellStanag556 (well-class match), AttachmentOpticsRIS1913 (slot type match), MagazineTemplate (direct prefab ref), LoadoutSlotInfo (character slot).
   */
  evidence?: string
}
