/* eslint-disable */
/**
 * @generated by packages/tbd-schema/scripts/codegen.mjs — DO NOT EDIT BY HAND.
 * Regenerate: make schema-codegen
 * Source: packages/tbd-schema/schema/registry-items.schema.json
 */

/**
 * Flat catalog of placeable/equipable engine items exported from the TBD-Content Workbench. Items are identified by their full Enfusion ResourceName (resource_name). This is a separate layer from the alias spawn registry (registry.schema.json): the alias registry maps mission aliases to GUIDs for spawn, this catalog drives the web Virtual Arsenal (browse, seed/import, loadout build). v2 (T-150): kind vocabulary expanded for the universal mod-agnostic scanner; optional addons[] records the Workbench scan set.
 */
export interface TBDRegistryItems {
  registryItemsVersion: string
  modpackId: string
  generatedAt?: string
  /**
   * Workbench addons loaded during the export (the scan set). Optional for v1 envelopes; the universal exporter (T-150) always writes it.
   */
  addons?: Addon[]
  /**
   * @minItems 1
   */
  items: [Item, ...Item[]]
}
export interface Addon {
  /**
   * Addon GUID from GameProject.GetLoadedAddons.
   */
  guid: string
  /**
   * Addon ID (GameProject.GetAddonID), e.g. ArmaReforger.
   */
  name: string
  /**
   * Human title (GameProject.GetAddonTitle).
   */
  title?: string
  /**
   * GameProject.IsVanillaAddon.
   */
  vanilla?: boolean
}
export interface Item {
  /**
   * Enfusion ResourceName ({GUID}Prefabs/.../File.et) used by Resource.Load.
   */
  resource_name: string
  display_name: string
  /**
   * Slash-delimited browse path, e.g. NATO/Rifleman.
   */
  category: string
  icon_url?: string
  /**
   * v3 (T-068.10.2) classification. Phase 1 kinds remain valid; gear_uniform is retired (0 rows — split into gear_jacket/gear_pants/gear_boots) but still accepted; 'other' is the escape hatch and its count must be reported in export verify logs. Taxonomy: .ai/artifacts/ace_arsenal_taxonomy_map.md.
   */
  kind:
    | 'character'
    | 'gear_primary'
    | 'gear_handgun'
    | 'gear_launcher'
    | 'gear_throwable'
    | 'gear_explosive'
    | 'gear_uniform'
    | 'gear_jacket'
    | 'gear_pants'
    | 'gear_boots'
    | 'gear_vest'
    | 'gear_armored_vest'
    | 'gear_helmet'
    | 'gear_backpack'
    | 'gear_glasses'
    | 'gear_gloves'
    | 'gear_binoculars'
    | 'gear_item'
    | 'magazine'
    | 'ammo'
    | 'optic'
    | 'attachment'
    | 'vehicle'
    | 'vehicle_weapon'
    | 'crate'
    | 'other'
  /**
   * True for non-placeable template prefabs (filename *_base.et / display '* Base'). Kept in the catalog (bases carry classification signals for descendants) but hidden from loadout pickers.
   */
  abstract?: boolean
  /**
   * SCR_EArsenalItemType flag name (e.g. RIFLE, NON_LETHAL_THROWABLE) when the item appears in a faction EntityCatalog SCR_ArsenalItem entry (Tier-B classification metadata). Absent when no catalog entry exists.
   */
  arsenal_type?: string
  /**
   * ItemPhysicalAttributes.Weight in kilograms (API-documented unit), read from the prefab ancestry chain. Absent when the value is an engine class default not serialized in the prefab — never guessed.
   */
  weight_kg?: number
  /**
   * ItemPhysicalAttributes.ItemVolume in cubic centimetres (API-documented unit), read from the prefab ancestry chain. Absent when the value is an engine class default not serialized in the prefab — never guessed.
   */
  volume_cm3?: number
  /**
   * Per-item mod provenance: the addon ID this prefab was scanned from. Must match an addons[].name entry (strict check in validate.mjs); vanilla-ness derives from addons[].vanilla — no separate flag to drift.
   */
  addon?: string
  /**
   * Container carry capacity (storage component m_fMaxWeight, kg) for items that ARE containers (vests/backpacks/jackets). Absent when the prefab relies on the engine class default — never guessed. Feeds the later cargo-budget slice.
   */
  max_weight_kg?: number
  /**
   * Container volume capacity (storage component MaxCumulativeVolume, cm³) for items that ARE containers. Absent when the prefab relies on the engine class default — never guessed. Feeds the later cargo-budget slice.
   */
  max_volume_cm3?: number
  /**
   * T-068.10.5: set on factory attachment/camo CONFIGURATIONS of a base weapon (same family prefix, magwell, attachment-slot-type set and mesh — only pre-mounted attachments/materials differ, e.g. 'Rifle AK74N 1P29' → 'Rifle AK74N'). Points at the immediate parent item (must exist in the envelope — strict check in validate.mjs). Pickers hide variant rows like abstracts; the census artifact t068_10_5_weapon_families.md carries the per-weapon evidence.
   */
  variant_of?: string
}
