/* eslint-disable */
/**
 * @generated by packages/tbd-schema/scripts/codegen.mjs — DO NOT EDIT BY HAND.
 * Regenerate: make schema-codegen
 * Source: packages/tbd-schema/schema/registry-items.schema.json
 */

/**
 * Flat catalog of placeable/equipable engine items exported from the TBD-Content Workbench. Items are identified by their full Enfusion ResourceName (resource_name). This is a separate layer from the alias spawn registry (registry.schema.json): the alias registry maps mission aliases to GUIDs for spawn, this catalog drives the web Virtual Arsenal (browse, seed/import, loadout build).
 */
export interface TBDRegistryItems {
  registryItemsVersion: string
  modpackId: string
  generatedAt?: string
  /**
   * @minItems 1
   */
  items: [Item, ...Item[]]
}
export interface Item {
  /**
   * Enfusion ResourceName ({GUID}Prefabs/.../File.et) used by Resource.Load.
   */
  resource_name: string
  display_name: string
  /**
   * Slash-delimited browse path, e.g. NATO/Rifleman.
   */
  category: string
  icon_url?: string
  kind: 'character' | 'gear_primary' | 'gear_uniform' | 'gear_vest' | 'gear_helmet'
}
