pub const AUTO_HEADER: &str = "<!-- AUTO-GENERATED by ./scripts/ticket sync — DO NOT EDIT -->\n\n";

pub const FORBIDDEN_PHANTOM_IDS: &[&str] = &[
    "T-007", "T-014", "T-015", "T-016", "T-017", "T-026", "T-027", "T-028", "T-041", "T-042",
    "T-044", "T-051",
];

/// Note: en-dashes U+2013 in P0–P2 / P0–P3 (matches Python STRICT_LEGACY exactly).
pub const STRICT_LEGACY: &str = concat!(
    r"\bP[0-3]-[0-9]{2}\b|\bP[0-3]-0[0-9]\b",
    r"|Eden P[0-3]|Eden P0|P0–P2|P0-P3|P0–P3",
    r"|\bP0 registry\b|\bP1 feel\b",
    r"|\bFD-0[0-9]{1,2}\b|\bFD-0xx\b|\bFD backlog\b",
    r"|\bBE-0[0-9]{1,2}\b|\bBE-0xx\b|\bBE backlog\b",
    r"|Track [ABC]\b|Tracks [ABC]-[ABC]-[ABC]|Tracks [ABC]-[ABC]",
    r"|\bA-0[0-9]\b|\bB-0[0-9]\b|\bC-0[0-9]\b",
    r#"|\"gap\":\s*\"P[0-3]-"#,
);

pub const EXEMPT_SCAN_PREFIXES: &[&str] = &[
    ".ai/artifacts/eden-wiki/",
    "frontend/src/stitch-exports/",
    "docs/specs/macOS_Blueprints/",
    "docs/specs/Mission_Creator_Mock_Up/",
    ".stitch-backup-exports/",
];

pub const STATUS_MARKER_START: &str = "<!-- ticket-sync:status:start -->";
pub const STATUS_MARKER_END: &str = "<!-- ticket-sync:status:end -->";
pub const NEXT_MARKER_START: &str = "<!-- ticket-sync:next:start -->";
pub const NEXT_MARKER_END: &str = "<!-- ticket-sync:next:end -->";

pub const VALID_TARGETS: &[&str] = &["website", "mod", "shared", "root"];
pub const VALID_EXECUTORS: &[&str] = &["claude-code", "cursor-docs", "workbench", "human", "ci"];
pub const VALID_STREAMS: &[&str] = &[
    "mission-creator",
    "web-platform",
    "mod-framework",
    "shared-schema",
    "content",
    "infra",
    "voip-partner",
];
