//! T-912.2 — `.ai/tickets/wave.lock`: the compiled wave plan.
//!
//! Tickets are the only source of `owns` / `depends_on` / `pack_last` (T-912.1). This module
//! COMPILES them into one committed TOML lock — `cargo xtask wave repack` is the ONLY legal
//! writer — and `cargo xtask wave check` recomputes and structurally compares. The two hand-kept
//! wave-plan TSVs died in the same commit as the first lock; the migration arm that read them
//! lives in [`crate::wave::legacy_plan`], the one file allowed to name them.
//!
//! ── LOCK SHAPE (pinned emit order; deterministic byte-for-byte) ──────────────────────────────
//!
//! ```toml
//! # auto-generated by cargo xtask wave repack — do not hand-edit
//! version = 1
//! max_concurrent = 8          # TBD_MAX_CONCURRENT at repack time, recorded
//! wave_base = 132             # newest non-disavowed close marker at repack; 0 = none reachable
//! pack_last = ["T-290"]
//! [[waves]]                    # n = 0 is the parking lot; open waves number wave_base+1 onward
//! n = 0
//! tickets = [...]
//! [[emptied]]                  # T-925: fully-shipped former open waves pending close —
//! n = 133                      # frozen {label, ticket set}; OMITTED entirely when none
//! tickets = [...]
//! [owns]                       # per-ticket snapshots, sorted maps
//! [depends_on]
//! ```
//!
//! `wave_base` and `pack_last` precede `[[waves]]` because TOML forbids a root-level value after
//! a table — that constraint, not taste, pins the order.
//!
//! ── NUMBERING — THE CLOSE-MARKER LEDGER (T-914) ──────────────────────────────────────────────
//!
//! Open waves are labeled `wave_base + 1` onward (T-925: past every pending emptied label too —
//! see §EMPTIED WAVES), where `wave_base` is the newest valid,
//! non-disavowed `wave N CLOSED` marker reachable from HEAD at repack time — HEAD included,
//! because the repack that follows a close ceremony runs with the fresh marker at HEAD
//! ([`crate::wave::base::newest_close_base`], which shares the gate's one subject authority).
//! Operator decision 2026-08-14: the lock CONTINUES the historical close ledger instead of
//! restarting at 1, so the ceremony's next `wave N CLOSED` subject is a number oracle 1
//! ([`crate::wave::base::wave_close_is_newest_wave`]) accepts instead of refuses. Nothing
//! hardcodes the base: a tree with no reachable marker — every scratch/stub/test root — derives
//! 0 and numbers 1..N, the pre-T-914 shape.
//!
//! `check` recomputes the base and reds on drift, naming the repack: a fresh close marker (or a
//! disavowal of the newest one) without a repack is exactly the stale-lock state this file
//! exists to refuse. It does NOT demand n-contiguity from the base — waves 1+ grouping AND
//! labels stay the packer's recorded choice (see CHECK below), and raw-TOML stub locks with
//! arbitrary n stay valid.
//!
//! ── EMPTIED WAVES (T-925) ────────────────────────────────────────────────────────────────────
//!
//! When every ticket of an open wave ships, the next repack parks them all in wave 0 and the
//! wave's label silently dissolves — which left `wave --close` with no reachable target ever:
//! `current_wave` names the first wave still holding UNSHIPPED work, and the finished wave it
//! should have closed no longer exists by the time close runs. So the repack FREEZES the
//! dissolving wave instead: its label and its exact ticket set become a pending `[[emptied]]`
//! entry, carried from the previous lock exactly like the wave-0 baseline (same
//! cannot-recompute-from-scratch class), and dropped the moment the ledger base reaches the
//! label — i.e. by the post-close repack, once that label's `wave N CLOSED` marker landed.
//! `wave --close` targets the OLDEST pending entry (the marker oracle accepts only base+1, so a
//! queue drains in ledger order). Open waves number past every pending label
//! (`max(wave_base, highest pending) + 1`), so a reserved label is never reissued while it
//! waits. Partial ships record nothing — only a wave whose whole set landed empties.
//!
//! ── WAVE 0 ───────────────────────────────────────────────────────────────────────────────────
//!
//! Wave 0 is the frozen ledger of everything undispatchable: the previous lock's wave 0, plus
//! every ticket whose status is shipped/cancelled/deferred or whose executor is not claude-code.
//! It subsumes the old generation-floor env knob — landed generations live here, so waves 1+
//! are open work only and `current_wave` is simply the first wave n>0 holding an unshipped id.
//! A ticket that becomes dispatchable again (a reopened deferral) LEAVES wave 0 — it is open,
//! so it must pack. Order edits never move wave 0: membership keys off status/executor only.
//! Idea-status claude-code tickets are in neither wave 0 nor waves 1+ — same limbo the TSV gave
//! unfiled tickets — and the `slice-collisions` unplanned warning names the dispatchable ones.
//!
//! ── PACKING (waves 1+) ───────────────────────────────────────────────────────────────────────
//!
//! The live greedy, unchanged from `slice-collisions --repack` (T-620): file-disjoint `owns`
//! per wave (prefix containment collides), `depends_on` forces a dependent strictly later than
//! its dependency's wave, `pack_last` tickets trail in singleton waves, cap `TBD_MAX_CONCURRENT`
//! default 8. Candidates sort by ticket `order`, tie-broken by id — filesystem order is
//! FORBIDDEN as a sort key (the id tie-break is what makes equal-order children deterministic).
//!
//! A dependency edge gates packing ONLY when its target is itself a dispatchable candidate.
//! A target that is shipped/cancelled is satisfied history; a target that is idea/deferred or
//! executor-gated can never pack, and letting it block would deadlock the whole queue on one
//! edge (live case at cutover: T-212 → T-257, status idea). Those edges are WARNED about at
//! repack, never silently honoured and never silently dropped.
//!
//! ── CHECK ────────────────────────────────────────────────────────────────────────────────────
//!
//! `wave check` recomputes wave 0 (baseline = the committed lock's wave 0) and every snapshot
//! from the ticket files, structurally compares against the committed lock, and validates the
//! committed waves 1+: exactly-dispatchable membership, no duplicates, per-wave owns
//! disjointness, cap, pack_last trailing. A MISSING lock is a DidNotRun refusal — exit nonzero,
//! never an empty-plan success (the `plan_rows` `unwrap_or_default` false-green class this
//! program exists to kill).
//!
//! Waves 1+ GROUPING is the packer's recorded choice and is validated, not re-derived: the
//! migration lock froze the committed TSV groups verbatim (T-912.2 must-ship 3), and that
//! grouping predates T-912.1's merged dependency edges — it holds one known inversion (T-212 in
//! an earlier wave than its dependency T-685). The packer enforces dependency order at every
//! later repack; check enforcing it retroactively would refuse the migration lock itself.
//! Same reason check borrows the lock's recorded `max_concurrent` instead of the ambient env:
//! the lock is self-describing, and a different shell must not turn a committed plan red.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use tbd_tickets::{StatusName, Ticket};

pub const LOCK_REL: &str = ".ai/tickets/wave.lock";
pub const LOCK_VERSION: u32 = 1;
const HEADER: &str = "# auto-generated by cargo xtask wave repack — do not hand-edit\n";

pub fn lock_path(root: &Path) -> PathBuf {
    root.join(LOCK_REL)
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct LockWave {
    pub n: u32,
    pub tickets: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct WaveLock {
    pub version: u32,
    pub max_concurrent: usize,
    /// T-914 — the close-marker ledger base open waves continue from (module header
    /// §NUMBERING). Serde-defaulted so pre-T-914 lock blobs read at historical revisions and
    /// the raw-TOML stubs in `mod_wave_tests` keep parsing; ALWAYS emitted (even 0) by the
    /// deterministic render. Declared between `max_concurrent` and `pack_last` because struct
    /// order IS emit order, and root-level values must precede the `[[waves]]` tables.
    #[serde(default)]
    pub wave_base: u32,
    pub pack_last: Vec<String>,
    pub waves: Vec<LockWave>,
    /// T-925 — pending EMPTIED waves (module header §EMPTIED WAVES): open waves of the
    /// previous lock whose every ticket has shipped, frozen as {label, exact ticket set} by
    /// the repack that dissolved them, held until `wave --close` lands each label's marker.
    /// [`carry_emptied`] is the only producer. Serde-defaulted so pre-T-925 lock blobs (and
    /// the raw-TOML stubs) keep parsing; SKIPPED from the render when empty — an
    /// `emptied = []` root value after the `[[waves]]` tables would not even be valid TOML,
    /// and the empty case must render byte-identically to the pre-T-925 shape. Nonempty it
    /// renders as `[[emptied]]` tables between `[[waves]]` and `[owns]`, labels ascending.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub emptied: Vec<LockWave>,
    pub owns: BTreeMap<String, Vec<String>>,
    pub depends_on: BTreeMap<String, Vec<String>>,
}

impl WaveLock {
    pub fn tickets_in_wave(&self, n: u32) -> Vec<String> {
        self.waves
            .iter()
            .find(|w| w.n == n)
            .map(|w| w.tickets.clone())
            .unwrap_or_default()
    }

    pub fn open_ids(&self) -> Vec<String> {
        self.waves
            .iter()
            .filter(|w| w.n > 0)
            .flat_map(|w| w.tickets.iter().cloned())
            .collect()
    }
}

/// The per-ticket facts the compiler needs, from EVERY `.ai/tickets/T-*.toml` — children
/// included. NOT the parents-only registry loader; a child id like T-090.4 must be a candidate.
#[derive(Debug, Clone)]
pub struct TicketView {
    pub id: String,
    pub title: String,
    pub work: bool,
    pub status: StatusName,
    pub order: Option<i64>,
    pub executor: Option<String>,
    pub owns: Vec<String>,
    pub depends_on: Vec<String>,
    pub pack_last: bool,
}

impl TicketView {
    /// Can a slice agent take this ticket? Work + live status + claude-code executor
    /// (absent executor defaults to claude-code, as everywhere else in the pipeline).
    pub fn dispatchable(&self) -> bool {
        self.work
            && self.status.is_live()
            && self.executor.as_deref().unwrap_or("claude-code") == "claude-code"
    }

    /// Belongs in wave 0: landed or never agent-actionable. The status list mirrors the old
    /// registry `dispatchable()` refusals (the typed schema has no `blocked`); a non-claude-code
    /// executor is operator work by the D5 gate regardless of status.
    pub fn parked(&self) -> bool {
        matches!(
            self.status,
            StatusName::Shipped | StatusName::Cancelled | StatusName::Deferred
        ) || self
            .executor
            .as_deref()
            .map(|e| e != "claude-code")
            .unwrap_or(false)
    }
}

pub fn load_views(root: &Path) -> Result<Vec<TicketView>> {
    // T-916.2: the shared typed corpus (`tbd_tickets::store::Corpus`) replaced this module's
    // own directory walk — three near-duplicate walks existed (here, `check_open_work_owns`,
    // `slice_collisions::ticket_facts`) and the store is now the one substrate. Same
    // fail-closed contract (one unparseable file refuses the load, naming it), plus the
    // stem==id guarantee the raw walk never had. BTreeMap iteration is id-sorted — the same
    // stable order the old post-walk sort produced; it is diagnostics order only and NEVER a
    // packing sort key (candidates sort by (order, id) below; glob order is forbidden by the
    // program spec).
    let corpus = tbd_tickets::Corpus::load(root).map_err(|e| anyhow::anyhow!(e))?;
    let views = corpus
        .tickets
        .into_values()
        .map(|t| match t {
            Ticket::Program(p) => TicketView {
                id: p.id,
                title: p.title,
                work: false,
                status: p.status.name(),
                order: p.status.order(),
                executor: p.executor,
                owns: p.owns,
                depends_on: p.depends_on,
                pack_last: p.pack_last == Some(true),
            },
            Ticket::Work(w) => TicketView {
                id: w.id,
                title: w.title,
                work: true,
                status: w.status.name(),
                order: w.status.order(),
                executor: w.executor,
                owns: w.owns,
                depends_on: w.depends_on,
                pack_last: w.pack_last == Some(true),
            },
        })
        .collect();
    Ok(views)
}

pub fn max_concurrent() -> usize {
    std::env::var("TBD_MAX_CONCURRENT")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(8)
}

/// Two owns sets collide when any path pair is equal or one prefix-contains the other —
/// byte-for-byte the `slice-collisions` rule.
pub fn collides(a: &[String], b: &[String]) -> bool {
    for x in a {
        for y in b {
            if x == y
                || x.starts_with(&format!("{}/", y.trim_end_matches('/')))
                || y.starts_with(&format!("{}/", x.trim_end_matches('/')))
            {
                return true;
            }
        }
    }
    false
}

/// Corpus-wide snapshots: every nonempty `owns` / `depends_on`, every `pack_last = true`.
/// Corpus-wide (not lock-member-scoped) so the writer and the checker cannot disagree about
/// which tickets are in scope.
type Snapshots = (
    BTreeMap<String, Vec<String>>,
    BTreeMap<String, Vec<String>>,
    Vec<String>,
);

fn snapshots(views: &[TicketView]) -> Snapshots {
    let mut owns = BTreeMap::new();
    let mut deps = BTreeMap::new();
    let mut last = Vec::new();
    for v in views {
        if !v.owns.is_empty() {
            owns.insert(v.id.clone(), v.owns.clone());
        }
        if !v.depends_on.is_empty() {
            deps.insert(v.id.clone(), v.depends_on.clone());
        }
        if v.pack_last {
            last.push(v.id.clone());
        }
    }
    last.sort();
    (owns, deps, last)
}

/// Wave 0 = baseline ∪ parked − dispatchable, sorted by id (wave 0 ignores `order`).
///
/// The baseline union is what keeps wave 0 a LEDGER: an id whose ticket file later disappears
/// stays parked instead of silently vanishing from the plan. The dispatchable subtraction is
/// the one legal exit — a reopened ticket is open work and must pack, and listing it in both
/// halves would make the lock disagree with itself.
fn wave_zero(views: &[TicketView], baseline: &BTreeSet<String>) -> Vec<String> {
    let mut set: BTreeSet<String> = baseline.clone();
    for v in views {
        if v.parked() {
            set.insert(v.id.clone());
        }
    }
    for v in views {
        if v.dispatchable() {
            set.remove(&v.id);
        }
    }
    set.into_iter().collect()
}

/// T-925 — the `[[emptied]]` carry: which pending close targets does the new lock hold?
///
/// Same previous-lock carry class as the wave-0 baseline ([`repack_quiet`] feeds the committed
/// lock in; a lockless tree carries nothing):
///
///   * every pending entry of the previous lock survives UNTIL ITS MARKER LANDS — an entry
///     whose label is at or below the fresh ledger base drops, because that label's
///     `wave N CLOSED` marker is now in history (the post-close repack is exactly this call);
///   * every previous OPEN wave above the base whose ticket set is now entirely
///     shipped/cancelled EMPTIES: its label and its exact ticket set freeze into an entry.
///     Shipped-or-cancelled mirrors `Registry::is_shipped` — the same "done" the close
///     ceremony's all-shipped validation re-checks against the tree — so the repack can never
///     record a target close would refuse on status grounds. A wave with any live ticket
///     records NOTHING (partial ships leave no trace), and a listed id with no ticket file is
///     not shipped — fail-closed, the wave stays un-emptied.
///
/// The frozen set is never recomputed or filtered afterwards: it is the ledger of what the
/// wave WAS when it emptied, which is what its close marker will name. Labels ascend in the
/// output; `check_as_errors` re-verifies that via the union numbering check.
fn carry_emptied(prev: Option<&WaveLock>, views: &[TicketView], wave_base: u32) -> Vec<LockWave> {
    let Some(prev) = prev else {
        return Vec::new();
    };
    let by_id: BTreeMap<&str, &TicketView> = views.iter().map(|v| (v.id.as_str(), v)).collect();
    let landed = |id: &String| {
        by_id
            .get(id.as_str())
            .map(|v| matches!(v.status, StatusName::Shipped | StatusName::Cancelled))
            .unwrap_or(false)
    };
    let mut out: Vec<LockWave> = prev
        .emptied
        .iter()
        .filter(|e| e.n > wave_base)
        .cloned()
        .collect();
    let pending: BTreeSet<u32> = out.iter().map(|e| e.n).collect();
    for w in &prev.waves {
        if w.n <= wave_base || pending.contains(&w.n) || w.tickets.is_empty() {
            continue;
        }
        if w.tickets.iter().all(landed) {
            out.push(w.clone());
        }
    }
    out.sort_by_key(|e| e.n);
    out
}

/// The live greedy over dispatchable candidates sorted by (`order`, id).
///
/// Returns the packed waves (1..N by position). Dependency edges whose target cannot ever pack
/// (not dispatchable, not shipped/cancelled) are collected into `warnings` and do not gate —
/// see the module header for the T-212 → T-257 case that forces this.
fn greedy_waves(
    views: &[TicketView],
    cap: usize,
    warnings: &mut Vec<String>,
) -> Result<Vec<Vec<String>>> {
    let by_id: BTreeMap<&str, &TicketView> = views.iter().map(|v| (v.id.as_str(), v)).collect();
    let mut cands: Vec<&TicketView> = views.iter().filter(|v| v.dispatchable()).collect();
    cands.sort_by(|a, b| {
        a.order
            .unwrap_or(i64::MAX)
            .cmp(&b.order.unwrap_or(i64::MAX))
            .then_with(|| a.id.cmp(&b.id))
    });
    let disp_ids: HashSet<&str> = cands.iter().map(|v| v.id.as_str()).collect();

    for c in &cands {
        for d in &c.depends_on {
            if disp_ids.contains(d.as_str()) {
                continue; // schedulable — the packer orders around it
            }
            let landed = by_id
                .get(d.as_str())
                .map(|t| matches!(t.status, StatusName::Shipped | StatusName::Cancelled))
                .unwrap_or(false);
            if !landed {
                let what = by_id
                    .get(d.as_str())
                    .map(|t| t.status.as_str())
                    .unwrap_or("no ticket file");
                warnings.push(format!(
                    "{} depends_on {d} ({what}) — target can never pack, edge does not gate",
                    c.id
                ));
            }
        }
    }

    let last: Vec<&TicketView> = cands.iter().copied().filter(|v| v.pack_last).collect();
    let mut remaining: Vec<&TicketView> = cands.iter().copied().filter(|v| !v.pack_last).collect();
    // An edge blocks while its target is a dispatchable candidate not yet packed in an EARLIER
    // wave — `packed` updates between waves, so same-wave dependency is impossible.
    let mut packed: HashSet<String> = HashSet::new();
    let blocked = |v: &TicketView, packed: &HashSet<String>| {
        v.depends_on
            .iter()
            .any(|d| disp_ids.contains(d.as_str()) && !packed.contains(d))
    };

    let mut waves: Vec<Vec<String>> = Vec::new();
    while !remaining.is_empty() {
        let mut wave: Vec<String> = Vec::new();
        let mut used: Vec<&[String]> = Vec::new();
        for c in &remaining {
            if blocked(c, &packed) {
                continue;
            }
            if used.iter().any(|u| collides(&c.owns, u)) {
                continue;
            }
            wave.push(c.id.clone());
            used.push(&c.owns);
            if wave.len() >= cap {
                break;
            }
        }
        if wave.is_empty() {
            // Everything left is dep-blocked with nothing packable underneath: a cycle in the
            // dispatchable graph. That is a bug worth shouting about, exactly as the TSV-era
            // repack did.
            let free: Vec<&TicketView> = remaining
                .iter()
                .copied()
                .filter(|v| !blocked(v, &packed))
                .collect();
            if free.is_empty() {
                let ids: Vec<&str> = remaining.iter().take(8).map(|v| v.id.as_str()).collect();
                bail!("depends_on deadlock: {ids:?} — check those tickets' depends_on edges");
            }
            wave.push(free[0].id.clone());
        }
        let picked: HashSet<&str> = wave.iter().map(String::as_str).collect();
        remaining.retain(|v| !picked.contains(v.id.as_str()));
        for id in &wave {
            packed.insert(id.clone());
        }
        waves.push(wave);
    }
    // pack_last tickets trail, one singleton wave each, in candidate order.
    for v in last {
        packed.insert(v.id.clone());
        waves.push(vec![v.id.clone()]);
    }
    Ok(waves)
}

/// T-914 — the ledger base the lock records: derived from `root`'s git history at pack time,
/// never from a constant. 0 when no marker is reachable (scratch dirs, stub roots, unit tests,
/// a tree before its first close), which keeps open waves at the pre-T-914 1..N. The u32
/// conversion is total in practice — the subject authority admits digits only, and no ledger
/// approaches the boundary; a number that somehow overflows is treated as no marker.
fn ledger_base(root: &Path) -> Result<u32> {
    // Err is the shallow-clone refusal — an unreadable ledger never derives a base.
    Ok(crate::wave::base::newest_close_base(root)
        .map_err(|e| anyhow::anyhow!(e))?
        .and_then(|n| u32::try_from(n).ok())
        .unwrap_or(0))
}

fn assemble(
    views: &[TicketView],
    baseline: &BTreeSet<String>,
    open_waves: Vec<Vec<String>>,
    cap: usize,
    wave_base: u32,
    emptied: Vec<LockWave>,
) -> WaveLock {
    let (owns, depends_on, pack_last) = snapshots(views);
    let mut waves = Vec::new();
    let zero = wave_zero(views, baseline);
    if !zero.is_empty() {
        waves.push(LockWave {
            n: 0,
            tickets: zero,
        });
    }
    // Open waves continue the close-marker ledger (module header §NUMBERING), numbering past
    // every PENDING emptied label too (T-925): those labels are reserved for their close
    // markers, so the first open wave is max(wave_base, highest pending) + 1 and a relabel
    // can never collide with a wave that is waiting to close. Wave 0 is a LEDGER, not a
    // schedule — its label never moves off 0.
    let floor = emptied.iter().map(|e| e.n).fold(wave_base, u32::max);
    for (i, tickets) in open_waves.into_iter().enumerate() {
        waves.push(LockWave {
            n: floor + 1 + i as u32,
            tickets,
        });
    }
    WaveLock {
        version: LOCK_VERSION,
        max_concurrent: cap,
        wave_base,
        pack_last,
        waves,
        emptied,
        owns,
        depends_on,
    }
}

/// Compile the lock from the ticket tree: wave 0 on `baseline`, open waves from the greedy,
/// labeled from the close-marker ledger past every pending emptied label, and the emptied
/// section carried from `prev` — the previous committed lock. `None` compiles a tree with no
/// lock history and carries nothing (first-ever compile, migration, fixture trees).
pub fn compile(
    root: &Path,
    baseline: &BTreeSet<String>,
    prev: Option<&WaveLock>,
) -> Result<WaveLock> {
    let views = load_views(root)?;
    let mut warnings = Vec::new();
    let cap = max_concurrent();
    let open = greedy_waves(&views, cap, &mut warnings)?;
    for w in &warnings {
        eprintln!("wave repack: warning: {w}");
    }
    let wave_base = ledger_base(root)?;
    let emptied = carry_emptied(prev, &views, wave_base);
    Ok(assemble(&views, baseline, open, cap, wave_base, emptied))
}

pub fn render(lock: &WaveLock) -> Result<String> {
    let body = toml::to_string(lock).context("render wave.lock")?;
    let mut out = String::with_capacity(HEADER.len() + body.len());
    out.push_str(HEADER);
    out.push_str(&body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

pub fn parse(text: &str) -> Result<WaveLock> {
    toml::from_str(text).context("parse wave.lock (TOML)")
}

/// The DidNotRun refusal every reader shares: an absent lock is a refusal, never an empty plan.
pub fn missing_lock_error(root: &Path) -> String {
    format!(
        "{} missing — DidNotRun: run `cargo xtask wave repack`. A missing lock is a refusal, never an empty plan.",
        lock_path(root).display()
    )
}

pub fn load(root: &Path) -> Result<WaveLock> {
    let p = lock_path(root);
    if !p.is_file() {
        bail!("{}", missing_lock_error(root));
    }
    let text = std::fs::read_to_string(&p).with_context(|| p.display().to_string())?;
    parse(&text)
}

pub fn write(root: &Path, lock: &WaveLock) -> Result<()> {
    let p = lock_path(root);
    std::fs::write(&p, render(lock)?).with_context(|| p.display().to_string())?;
    Ok(())
}

/// Refresh the lock after a registry status write (the `ticket ship` / `ticket set-status`
/// bookkeeping hook, and `platform wave land`'s final step). Same writer as `wave repack`;
/// wave 0 baseline carries over from the previous lock when one exists.
pub fn repack_quiet(root: &Path) -> Result<WaveLock> {
    if crate::wave::legacy_plan::any_tsv_present(root) {
        return migrate_from_tsv(root);
    }
    // The previous committed lock is BOTH carries: its wave 0 is the parked baseline, and its
    // open waves + pending entries feed the emptied carry (T-925, [`carry_emptied`]).
    let prev = load(root).ok(); // first-ever compile on a lockless tree carries nothing
    let baseline: BTreeSet<String> = prev
        .as_ref()
        .map(|p| p.tickets_in_wave(0).into_iter().collect())
        .unwrap_or_default();
    let lock = compile(root, &baseline, prev.as_ref())?;
    write(root, &lock)?;
    Ok(lock)
}

/// One-shot cutover: waves 1+ are the committed TSV open-id groups (platform then mod, label
/// groups in file order, relabeled 1..N), wave 0 is every non-dispatchable TSV id plus every
/// parked ticket. Deletes both TSVs — the lock and the deletion ride the same commit.
fn migrate_from_tsv(root: &Path) -> Result<WaveLock> {
    let views = load_views(root)?;
    let by_id: BTreeMap<&str, &TicketView> = views.iter().map(|v| (v.id.as_str(), v)).collect();
    let rows = crate::wave::legacy_plan::working_tree_rows(root)?;

    let mut label_order: Vec<&str> = Vec::new();
    let mut groups: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    let mut wave0_tsv: BTreeSet<String> = BTreeSet::new();
    for (label, id) in &rows {
        let disp = by_id.get(id.as_str()).map(|v| v.dispatchable()) == Some(true);
        if disp {
            if !groups.contains_key(label.as_str()) {
                label_order.push(label.as_str());
            }
            groups.entry(label.as_str()).or_default().push(id.as_str());
        } else {
            wave0_tsv.insert(id.clone());
        }
    }
    let open: Vec<Vec<String>> = label_order
        .iter()
        .map(|l| groups[l].iter().map(|s| s.to_string()).collect())
        .collect();

    // T-914: the migration arm numbers from the ledger too. The T-912.2 cutover relabeled the
    // TSV groups 1..N, but that lock has already landed in real history — this arm is only
    // reachable on a hypothetical TSV-bearing tree, and numbering it off the ledger keeps the
    // base check green there instead of red-on-arrival. No emptied carry: the TSV era
    // predates the section, and a TSV-bearing tree has no previous LOCK to carry from.
    let lock = assemble(
        &views,
        &wave0_tsv,
        open,
        max_concurrent(),
        ledger_base(root)?,
        Vec::new(),
    );
    write(root, &lock)?;
    crate::wave::legacy_plan::delete_tsvs(root)?;
    Ok(lock)
}

fn summary(lock: &WaveLock) -> String {
    let open: usize = lock
        .waves
        .iter()
        .filter(|w| w.n > 0)
        .map(|w| w.tickets.len())
        .sum();
    let n_open = lock.waves.iter().filter(|w| w.n > 0).count();
    let parked = lock
        .waves
        .iter()
        .find(|w| w.n == 0)
        .map(|w| w.tickets.len())
        .unwrap_or(0);
    let base = format!("{open} open ticket(s) in {n_open} wave(s), {parked} parked at wave 0");
    // T-925: a pending emptied wave is the thing `wave --close` acts on — say so whenever one
    // exists; byte-identical summary when none does.
    match lock.emptied.len() {
        0 => base,
        k => format!("{base}, {k} emptied wave(s) pending close"),
    }
}

pub fn cmd_repack(root: &Path) -> Result<u8> {
    let migrated = crate::wave::legacy_plan::any_tsv_present(root);
    let lock = repack_quiet(root)?;
    if migrated {
        println!("wave.lock: migrated from the committed wave-plan TSVs (both deleted)");
    }
    println!("wrote {}: {}", LOCK_REL, summary(&lock));
    Ok(0)
}

/// All check findings as error strings — embedded verbatim into `ticket check`.
pub fn check_as_errors(root: &Path) -> Vec<String> {
    let lock = match load(root) {
        Ok(l) => l,
        Err(e) => return vec![format!("{e:#}")],
    };
    let views = match load_views(root) {
        Ok(v) => v,
        Err(e) => return vec![format!("wave check: {e:#}")],
    };
    let mut errors = Vec::new();

    if lock.version != LOCK_VERSION {
        errors.push(format!(
            "wave.lock version {} != {LOCK_VERSION} — regenerate with `cargo xtask wave repack`",
            lock.version
        ));
    }

    // T-914: the recorded ledger base must match a fresh derivation from git history. A close
    // marker landing (or the newest one being disavowed) without a repack leaves every open
    // wave labeled off the old base — this error is what drives the close → check-red → repack
    // loop. Deliberately NOT a contiguity rule: beyond the strictly-increasing check below,
    // open-wave labels are the packer's recorded choice, and raw-TOML stubs with arbitrary n
    // (mod_wave_tests uses 99) must stay green.
    let derived_base = match ledger_base(root) {
        Ok(want_base) => {
            if lock.wave_base != want_base {
                errors.push(format!(
                    "wave.lock wave_base {} is stale — the close-marker ledger derives {want_base}: run `cargo xtask wave repack`",
                    lock.wave_base
                ));
            }
            Some(want_base)
        }
        Err(e) => {
            errors.push(format!("wave.lock base derivation refused: {e}"));
            None
        }
    };

    // Wave numbering: strictly increasing, wave 0 first when present, no duplicate n —
    // across the UNION of open-wave labels and pending emptied labels (T-925). Emptied
    // labels are RESERVED numbers sitting between wave_base and the open waves (the packer
    // numbers open waves past them), so the one legal ascending order is wave 0, then every
    // pending emptied label, then every open wave; a collision or inversion anywhere in
    // that union is red here.
    let mut ns: Vec<u32> = lock
        .waves
        .iter()
        .filter(|w| w.n == 0)
        .map(|w| w.n)
        .collect();
    ns.extend(lock.emptied.iter().map(|e| e.n));
    ns.extend(lock.waves.iter().filter(|w| w.n > 0).map(|w| w.n));
    let mut sorted = ns.clone();
    sorted.sort_unstable();
    sorted.dedup();
    if ns != sorted {
        errors.push(format!(
            "wave.lock wave numbers (wave 0, pending emptied, open waves) are not strictly increasing: {ns:?}"
        ));
    }

    // Wave 0 recompute against the committed lock's own baseline.
    let baseline: BTreeSet<String> = lock.tickets_in_wave(0).into_iter().collect();
    let expect_zero = wave_zero(&views, &baseline);
    let got_zero = lock.tickets_in_wave(0);
    if expect_zero != got_zero {
        let exp: BTreeSet<&String> = expect_zero.iter().collect();
        let got: BTreeSet<&String> = got_zero.iter().collect();
        let missing: Vec<&&String> = exp.difference(&got).take(10).collect();
        let extra: Vec<&&String> = got.difference(&exp).take(10).collect();
        errors.push(format!(
            "wave.lock wave 0 is stale — missing {missing:?}, extra {extra:?}: run `cargo xtask wave repack`"
        ));
    }

    // Snapshots must equal the tickets, corpus-wide.
    let (owns, deps, last) = snapshots(&views);
    for (name, want, got) in [
        ("owns", &owns, &lock.owns),
        ("depends_on", &deps, &lock.depends_on),
    ] {
        if want != got {
            let mut diffs: Vec<String> = Vec::new();
            for (k, v) in want {
                if got.get(k) != Some(v) {
                    diffs.push(k.clone());
                }
            }
            for k in got.keys() {
                if !want.contains_key(k) {
                    diffs.push(k.clone());
                }
            }
            diffs.sort();
            diffs.dedup();
            diffs.truncate(10);
            errors.push(format!(
                "wave.lock {name} snapshot disagrees with the ticket files on {diffs:?} — run `cargo xtask wave repack`"
            ));
        }
    }
    if last != lock.pack_last {
        errors.push(format!(
            "wave.lock pack_last {:?} disagrees with the ticket files {:?} — run `cargo xtask wave repack`",
            lock.pack_last, last
        ));
    }

    // Waves 1+: every id dispatchable today, no id listed twice anywhere, per-wave owns
    // disjoint, cap respected, pack_last trailing as singletons. Grouping itself is the
    // packer's recorded choice — see the module header for why dependency order is enforced
    // at repack, not here.
    let by_id: BTreeMap<&str, &TicketView> = views.iter().map(|v| (v.id.as_str(), v)).collect();
    let mut seen: HashSet<&str> = got_zero.iter().map(String::as_str).collect();
    let mut past_pack_last = false;
    for w in lock.waves.iter().filter(|w| w.n > 0) {
        if w.tickets.is_empty() {
            errors.push(format!("wave.lock wave {} is empty", w.n));
        }
        if w.tickets.len() > lock.max_concurrent {
            errors.push(format!(
                "wave.lock wave {} holds {} tickets over the recorded cap {}",
                w.n,
                w.tickets.len(),
                lock.max_concurrent
            ));
        }
        let is_last_wave = w.tickets.iter().any(|t| lock.pack_last.contains(t));
        if is_last_wave && w.tickets.len() > 1 {
            errors.push(format!(
                "wave.lock wave {} mixes pack_last with other tickets",
                w.n
            ));
        }
        if past_pack_last && !is_last_wave {
            errors.push(format!(
                "wave.lock wave {} follows a pack_last wave but is not one — pack_last tickets trail",
                w.n
            ));
        }
        past_pack_last |= is_last_wave;
        for t in &w.tickets {
            if !seen.insert(t.as_str()) {
                errors.push(format!("wave.lock lists {t} more than once"));
            }
            match by_id.get(t.as_str()) {
                None => errors.push(format!(
                    "wave.lock wave {} lists {t}, which has no ticket file — run `cargo xtask wave repack`",
                    w.n
                )),
                Some(v) if !v.dispatchable() => errors.push(format!(
                    "wave.lock wave {} lists {t} ({}, executor {}) — not dispatchable; run `cargo xtask wave repack`",
                    w.n,
                    v.status.as_str(),
                    v.executor.as_deref().unwrap_or("claude-code"),
                )),
                Some(_) => {}
            }
        }
        for i in 0..w.tickets.len() {
            for j in (i + 1)..w.tickets.len() {
                let a = by_id.get(w.tickets[i].as_str()).map(|v| v.owns.as_slice());
                let b = by_id.get(w.tickets[j].as_str()).map(|v| v.owns.as_slice());
                if let (Some(a), Some(b)) = (a, b) {
                    if collides(a, b) {
                        errors.push(format!(
                            "wave.lock wave {}: {} and {} own overlapping paths — never the same wave",
                            w.n, w.tickets[i], w.tickets[j]
                        ));
                    }
                }
            }
        }
    }

    // ── T-925: the pending [[emptied]] section — repack-recorded close targets ──────────────
    // Like the wave-0 baseline, entries CARRY from the previous lock at repack time (the
    // frozen {label, ticket set} of an open wave whose every ticket had shipped) and CANNOT be
    // recomputed from scratch here — at check time there is no previous lock to read, only the
    // committed one. So this validates INVARIANTS, not a fresh derivation: every label above
    // wave_base (at-or-below means its close marker landed and the repack must drop it), sets
    // nonempty, every listed ticket shipped/cancelled in the current tree (the same "done" the
    // close ceremony re-verifies before writing a marker), and the carry rule itself as a
    // FIXPOINT — running the writer's own carry with this lock as its previous must reproduce
    // the section (that drops landed labels and records any fully-shipped open wave a stale
    // lock left behind). Ascending labels and emptied/open disjointness are already pinned by
    // the union numbering check above. A hand-edit INSIDE a frozen set that stays nonempty and
    // all-shipped is not detectable from the tree, exactly as a hand-edit to the file-less
    // half of the wave-0 baseline is not — the lock is the only record of what the wave was.
    for e in &lock.emptied {
        if e.n <= lock.wave_base {
            errors.push(format!(
                "wave.lock emptied wave {} is at or below wave_base {} — its close marker landed: run `cargo xtask wave repack`",
                e.n, lock.wave_base
            ));
        }
        if e.tickets.is_empty() {
            errors.push(format!(
                "wave.lock emptied wave {} lists no tickets — an empty set can never be recorded: run `cargo xtask wave repack`",
                e.n
            ));
        }
        for t in &e.tickets {
            let landed = by_id
                .get(t.as_str())
                .map(|v| matches!(v.status, StatusName::Shipped | StatusName::Cancelled))
                .unwrap_or(false);
            if !landed {
                let what = by_id
                    .get(t.as_str())
                    .map(|v| v.status.as_str())
                    .unwrap_or("no ticket file");
                errors.push(format!(
                    "wave.lock emptied wave {} lists {t} ({what}) — not shipped in the current tree",
                    e.n
                ));
            }
        }
    }
    if let Some(want_base) = derived_base {
        let want = carry_emptied(Some(&lock), &views, want_base);
        if want != lock.emptied {
            errors.push(format!(
                "wave.lock emptied section disagrees with the carry rule — pending labels {:?}, carry derives {:?}: run `cargo xtask wave repack`",
                lock.emptied.iter().map(|e| e.n).collect::<Vec<_>>(),
                want.iter().map(|e| e.n).collect::<Vec<_>>(),
            ));
        }
    }

    errors
}

pub fn cmd_check(root: &Path) -> Result<u8> {
    let errors = check_as_errors(root);
    if !errors.is_empty() {
        for e in &errors {
            eprintln!("ERROR: {e}");
        }
        bail!("wave check failed ({} error(s))", errors.len());
    }
    let lock = load(root)?;
    println!("wave.lock OK: {}", summary(&lock));
    Ok(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn scratch(tag: &str, files: &[(&str, &str)]) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("t912-lock-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        let tickets = dir.join(".ai/tickets");
        fs::create_dir_all(&tickets).unwrap();
        fs::write(tickets.join("ROOT"), "# ticket-registry root marker\n").unwrap();
        // T-917.2: `Corpus::load` resolves scope legality fail-closed — every scratch
        // tree carries the minimal vocabulary its fixtures use.
        fs::write(tickets.join("scope-vocab.toml"), "[repo.xtask]\n").unwrap();
        for (name, body) in files {
            fs::write(tickets.join(name), body).unwrap();
        }
        dir
    }

    fn work(id: &str, order: i64, owns: &[&str], deps: &[&str], status: &str) -> String {
        let owns = owns
            .iter()
            .map(|o| format!("\"{o}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let deps = deps
            .iter()
            .map(|d| format!("\"{d}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "id = \"{id}\"\nkind = \"work\"\ntitle = \"t {id}\"\nsummary = \"s\"\nclass = \"chore\"\nstatus = \"{status}\"\norder = {order}\ndepends_on = [{deps}]\nowns = [{owns}]\n\n[scope]\ndomain = \"repo\"\nlayer = \"xtask\"\n"
        )
    }

    #[test]
    fn overlapping_owns_never_share_a_wave() {
        let dir = scratch(
            "overlap",
            &[
                (
                    "T-1.toml",
                    &work("T-1", 10, &["crates/foo/a.rs"], &[], "queued"),
                ),
                (
                    "T-2.toml",
                    &work("T-2", 20, &["crates/foo/a.rs"], &[], "queued"),
                ),
            ],
        );
        let lock = compile(&dir, &BTreeSet::new(), None).unwrap();
        let open: Vec<&LockWave> = lock.waves.iter().filter(|w| w.n > 0).collect();
        assert_eq!(open.len(), 2, "colliding owns must split: {lock:?}");
        assert_eq!(open[0].tickets, vec!["T-1".to_string()]);
        assert_eq!(open[1].tickets, vec!["T-2".to_string()]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn dependent_packs_strictly_after_unshipped_dependency() {
        // T-2 has the LOWER order but depends on T-9 — it must still land strictly later.
        let dir = scratch(
            "deps",
            &[
                ("T-2.toml", &work("T-2", 10, &["a.rs"], &["T-9"], "queued")),
                ("T-9.toml", &work("T-9", 20, &["b.rs"], &[], "queued")),
            ],
        );
        let lock = compile(&dir, &BTreeSet::new(), None).unwrap();
        let wave_of = |id: &str| {
            lock.waves
                .iter()
                .find(|w| w.tickets.iter().any(|t| t == id))
                .map(|w| w.n)
                .unwrap()
        };
        assert!(
            wave_of("T-2") > wave_of("T-9"),
            "dependent same-or-earlier than dependency: {lock:?}"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn candidates_sort_by_order_then_id_never_glob_order() {
        // File names sort T-10 < T-9 lexically; order says T-9 first.
        let dir = scratch(
            "order",
            &[
                ("T-10.toml", &work("T-10", 20, &["a.rs"], &[], "queued")),
                ("T-9.toml", &work("T-9", 10, &["b.rs"], &[], "queued")),
                ("T-8.toml", &work("T-8", 20, &["c.rs"], &[], "queued")),
            ],
        );
        let lock = compile(&dir, &BTreeSet::new(), None).unwrap();
        // One wave (disjoint, under cap) — candidate order is (order, id): T-9, T-10, T-8→ tie
        // on 20 broken by id: "T-10" < "T-8" lexicographically.
        assert_eq!(
            lock.tickets_in_wave(1),
            vec!["T-9".to_string(), "T-10".to_string(), "T-8".to_string()]
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn compile_render_is_deterministic_and_roundtrips() {
        let dir = scratch(
            "det",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["b/dir"], &["T-1"], "queued")),
                ("T-3.toml", &work("T-3", 30, &["c.rs"], &[], "shipped")),
            ],
        );
        let a = compile(&dir, &BTreeSet::new(), None).unwrap();
        let b = compile(&dir, &BTreeSet::new(), None).unwrap();
        assert_eq!(a, b);
        let ra = render(&a).unwrap();
        assert_eq!(
            ra,
            render(&b).unwrap(),
            "double compile must render identical bytes"
        );
        assert!(ra.starts_with(HEADER));
        assert!(ra.ends_with('\n'));
        let parsed = parse(&ra).unwrap();
        assert_eq!(parsed, a, "render → parse must be lossless");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn wave_zero_is_baseline_union_parked_minus_reopened() {
        let dir = scratch(
            "zero",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["b.rs"], &[], "shipped")),
            ],
        );
        let baseline: BTreeSet<String> = ["T-1".to_string(), "T-777".to_string()]
            .into_iter()
            .collect();
        let views = load_views(&dir).unwrap();
        // T-1 reopened → leaves wave 0; T-777 has no file → ledger keeps it; T-2 parked.
        assert_eq!(
            wave_zero(&views, &baseline),
            vec!["T-2".to_string(), "T-777".to_string()]
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn missing_lock_is_a_did_not_run_refusal() {
        let dir = scratch("missing", &[]);
        let err = format!("{:#}", load(&dir).unwrap_err());
        assert!(
            err.contains("DidNotRun"),
            "want DidNotRun refusal, got: {err}"
        );
        assert!(err.contains("never an empty plan"), "got: {err}");
        let errs = check_as_errors(&dir);
        assert_eq!(errs.len(), 1);
        assert!(errs[0].contains("DidNotRun"));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn check_reds_on_perturbed_owns_and_edges_and_stale_membership() {
        let dir = scratch(
            "perturb",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["b.rs"], &["T-1"], "queued")),
            ],
        );
        let lock = compile(&dir, &BTreeSet::new(), None).unwrap();
        write(&dir, &lock).unwrap();
        assert!(check_as_errors(&dir).is_empty(), "fresh lock must be green");

        // Perturb owns without repack → red.
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["zzz.rs"], &[], "queued"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter().any(|e| e.contains("owns snapshot")),
            "owns perturbation must be red: {errs:?}"
        );
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["a.rs"], &[], "queued"),
        )
        .unwrap();
        assert!(check_as_errors(&dir).is_empty(), "restore must be green");

        // Remove a depends_on edge without repack → red.
        fs::write(
            dir.join(".ai/tickets/T-2.toml"),
            work("T-2", 20, &["b.rs"], &[], "queued"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter().any(|e| e.contains("depends_on snapshot")),
            "edge removal must be red: {errs:?}"
        );
        fs::write(
            dir.join(".ai/tickets/T-2.toml"),
            work("T-2", 20, &["b.rs"], &["T-1"], "queued"),
        )
        .unwrap();
        assert!(check_as_errors(&dir).is_empty());

        // Ship without repack → membership + wave 0 red.
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["a.rs"], &[], "shipped"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter().any(|e| e.contains("wave 0 is stale")),
            "ship without repack must red wave 0: {errs:?}"
        );
        assert!(
            errs.iter().any(|e| e.contains("not dispatchable")),
            "shipped id left in an open wave must be red: {errs:?}"
        );
        // Repack (the ship hook path) → green again, id parked.
        let lock = repack_quiet(&dir).unwrap();
        assert!(check_as_errors(&dir).is_empty());
        assert!(lock.tickets_in_wave(0).contains(&"T-1".to_string()));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn reorder_changes_open_waves_only_never_wave_zero() {
        let dir = scratch(
            "reorder",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["a.rs"], &[], "queued")),
                ("T-3.toml", &work("T-3", 30, &["c.rs"], &[], "shipped")),
            ],
        );
        let before = repack_quiet(&dir).unwrap();
        assert_eq!(before.tickets_in_wave(1), vec!["T-1".to_string()]);
        // Swap the two open orders.
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 40, &["a.rs"], &[], "queued"),
        )
        .unwrap();
        let after = repack_quiet(&dir).unwrap();
        assert_eq!(after.tickets_in_wave(1), vec!["T-2".to_string()]);
        assert_eq!(
            before.tickets_in_wave(0),
            after.tickets_in_wave(0),
            "order edits must never move wave 0"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    // ── T-914: the close-marker ledger base ─────────────────────────────────────────────────

    /// Run git in `dir` with a pinned identity — the metrics.rs scratch-repo pattern. Never a
    /// `Date`-dependent assertion downstream: subjects are the only degree of freedom.
    fn git_in_dir(dir: &Path, args: &[&str]) {
        let out = std::process::Command::new("git")
            .args([
                "-c",
                "user.email=t914@test",
                "-c",
                "user.name=t914",
                "-c",
                "commit.gpgsign=false",
            ])
            .args(args)
            .current_dir(dir)
            .output()
            .expect("spawn git");
        assert!(
            out.status.success(),
            "git {args:?}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    /// [`scratch`] plus a fabricated history: init, commit the ticket files, then one commit
    /// per subject. Each subject commit touches its own file so a later `git revert` of it is
    /// never empty.
    fn scratch_git(tag: &str, files: &[(&str, &str)], subjects: &[&str]) -> PathBuf {
        let dir = scratch(tag, files);
        git_in_dir(&dir, &["init", "-q"]);
        git_in_dir(&dir, &["add", "--", ".ai"]);
        git_in_dir(&dir, &["commit", "-q", "-m", "seed tickets"]);
        for (i, s) in subjects.iter().enumerate() {
            fs::write(dir.join(format!("c{i}.txt")), format!("{i}\n")).unwrap();
            git_in_dir(&dir, &["add", "--", &format!("c{i}.txt")]);
            git_in_dir(&dir, &["commit", "-q", "-m", s]);
        }
        dir
    }

    #[test]
    fn repack_continues_the_close_marker_ledger() {
        // The ledger's newest marker says wave 41; an ordinary commit sits at HEAD, so this is
        // the fallback (non-HEAD) derivation path. Colliding owns split T-1/T-2 into two waves.
        let dir = scratch_git(
            "ledger",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["a.rs"], &[], "queued")),
            ],
            &["wave 41 CLOSED — test ledger", "post-close housekeeping"],
        );
        let lock = repack_quiet(&dir).unwrap();
        assert_eq!(lock.wave_base, 41, "base = the newest close marker");
        let open: Vec<u32> = lock.waves.iter().filter(|w| w.n > 0).map(|w| w.n).collect();
        assert_eq!(open, vec![42, 43], "open waves continue base+1: {lock:?}");
        assert_eq!(lock.tickets_in_wave(42), vec!["T-1".to_string()]);
        assert!(
            check_as_errors(&dir).is_empty(),
            "fresh repack must be green"
        );
        let text = std::fs::read_to_string(lock_path(&dir)).unwrap();
        assert!(
            text.contains("\nwave_base = 41\n"),
            "wave_base is always emitted: {text}"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn shallow_clone_refuses_base_derivation() {
        // A depth-1 clone hides the ledger. Deriving base 0 there would be a wrong answer,
        // not a fallback (red against a full-history lock, silently green if the committed
        // base happens to be 0) — so both repack and check refuse loudly instead.
        let dir = scratch_git(
            "shallow-src",
            &[("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued"))],
            &["wave 41 CLOSED — test ledger", "post-close housekeeping"],
        );
        let lock = repack_quiet(&dir).unwrap();
        assert_eq!(lock.wave_base, 41, "full history derives the marker");
        let clone = dir.with_file_name("t914-shallow-clone");
        let _ = fs::remove_dir_all(&clone);
        git_in_dir(
            dir.parent().unwrap(),
            &[
                "clone",
                "-q",
                "--depth",
                "1",
                &format!("file://{}", dir.display()),
                clone.file_name().unwrap().to_str().unwrap(),
            ],
        );
        let err = repack_quiet(&clone).unwrap_err().to_string();
        assert!(err.contains("shallow"), "repack refuses on shallow: {err}");
        fs::copy(lock_path(&dir), lock_path(&clone)).unwrap();
        let errors = check_as_errors(&clone);
        assert!(
            errors.iter().any(|e| e.contains("base derivation refused")),
            "check refuses, never derives 0: {errors:?}"
        );
        let _ = fs::remove_dir_all(&dir);
        let _ = fs::remove_dir_all(&clone);
    }

    #[test]
    fn head_itself_as_the_marker_counts() {
        // The include-HEAD path: the marker IS HEAD — the state every post-close repack runs
        // in, and the one prev_wave_close deliberately refuses to see.
        let dir = scratch_git(
            "ledger-head",
            &[("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued"))],
            &["wave 41 CLOSED — test ledger"],
        );
        let lock = repack_quiet(&dir).unwrap();
        assert_eq!(lock.wave_base, 41, "a marker at HEAD is the base");
        assert_eq!(lock.tickets_in_wave(42), vec!["T-1".to_string()]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_disavowed_marker_is_not_a_base() {
        // wave 42's close is reverted — git revert writes the exact trailer the disavowal
        // evidence reads — so the base falls through to wave 41, mirroring prev_wave_close's
        // F6 handling on a root that is not the cwd.
        let dir = scratch_git(
            "ledger-disavow",
            &[("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued"))],
            &[
                "wave 41 CLOSED — test ledger",
                "wave 42 CLOSED — reverted below",
            ],
        );
        git_in_dir(&dir, &["revert", "--no-edit", "HEAD"]);
        let lock = repack_quiet(&dir).unwrap();
        assert_eq!(lock.wave_base, 41, "a reverted close is not a boundary");
        assert_eq!(lock.tickets_in_wave(42), vec!["T-1".to_string()]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn stale_base_reds_check_until_repack() {
        let dir = scratch_git(
            "ledger-stale",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["a.rs"], &[], "queued")),
            ],
            &["wave 41 CLOSED — test ledger"],
        );
        let lock = repack_quiet(&dir).unwrap();
        assert_eq!(lock.wave_base, 41);
        assert!(check_as_errors(&dir).is_empty());

        // A new close marker lands without a repack → the committed base is stale → red,
        // naming the fix. This is the close → check-red → repack loop.
        fs::write(dir.join("c-next.txt"), "x\n").unwrap();
        git_in_dir(&dir, &["add", "--", "c-next.txt"]);
        git_in_dir(
            &dir,
            &["commit", "-q", "-m", "wave 42 CLOSED — test ledger"],
        );
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter()
                .any(|e| e.contains("wave_base 41") && e.contains("wave repack")),
            "a stale base must be red and name the repack: {errs:?}"
        );

        // Repack renumbers from the new base → green, open waves from 43.
        let lock = repack_quiet(&dir).unwrap();
        assert_eq!(lock.wave_base, 42);
        assert_eq!(lock.tickets_in_wave(43), vec!["T-1".to_string()]);
        assert!(check_as_errors(&dir).is_empty());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn no_marker_tree_keeps_base_zero_and_waves_from_one() {
        let dir = scratch_git(
            "ledger-none",
            &[("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued"))],
            &["an ordinary commit, no marker anywhere"],
        );
        let lock = repack_quiet(&dir).unwrap();
        assert_eq!(lock.wave_base, 0, "no marker → base 0");
        assert_eq!(
            lock.tickets_in_wave(1),
            vec!["T-1".to_string()],
            "open waves stay 1..N on a markerless tree"
        );
        assert!(check_as_errors(&dir).is_empty());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn pre_t914_lock_without_wave_base_parses_as_zero() {
        // The serde default that keeps pre-T-914 lock blobs (read at historical revisions by
        // wave_plan_tickets_at) and the raw-TOML stubs in mod_wave_tests parsing.
        let text = "version = 1\nmax_concurrent = 8\npack_last = []\nwaves = []\n\n[owns]\n\n[depends_on]\n";
        let lock = parse(text).unwrap();
        assert_eq!(lock.wave_base, 0);
        assert!(
            render(&lock).unwrap().contains("\nwave_base = 0\n"),
            "the render emits wave_base even at 0"
        );
    }

    // ── T-925: the [[emptied]] section — pending close targets ──────────────────────────────

    /// The lock text from `[[emptied]]` to the section after it — the proof-block slice.
    fn emptied_slice(text: &str) -> &str {
        let start = text.find("[[emptied]]").expect("emptied section present");
        let end = text[start..]
            .find("\n[owns]")
            .map(|i| start + i)
            .unwrap_or(text.len());
        &text[start..end]
    }

    #[test]
    fn full_ship_freezes_the_wave_into_emptied_and_open_waves_number_past_it() {
        // Colliding owns split T-1/T-2 into waves 42 and 43 over ledger base 41.
        let dir = scratch_git(
            "emptied-full",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["a.rs"], &[], "queued")),
            ],
            &["wave 41 CLOSED — test ledger"],
        );
        let before = repack_quiet(&dir).unwrap();
        assert_eq!(before.tickets_in_wave(42), vec!["T-1".to_string()]);
        assert!(before.emptied.is_empty(), "nothing emptied yet: {before:?}");

        // Ship ALL of wave 42 (its whole set is T-1), then the ship-hook repack.
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["a.rs"], &[], "shipped"),
        )
        .unwrap();
        let lock = repack_quiet(&dir).unwrap();
        assert_eq!(lock.wave_base, 41, "no marker landed — base unchanged");
        assert_eq!(
            lock.emptied,
            vec![LockWave {
                n: 42,
                tickets: vec!["T-1".to_string()]
            }],
            "the dissolved wave froze: {lock:?}"
        );
        // Open waves number PAST the pending label: max(wave_base 41, pending 42) + 1.
        let open: Vec<u32> = lock.waves.iter().filter(|w| w.n > 0).map(|w| w.n).collect();
        assert_eq!(open, vec![43], "{lock:?}");
        assert_eq!(lock.tickets_in_wave(43), vec!["T-2".to_string()]);
        assert!(
            check_as_errors(&dir).is_empty(),
            "recorded state must be green"
        );
        let text = fs::read_to_string(lock_path(&dir)).unwrap();
        println!("── [[emptied]] block after the full-ship repack ──");
        println!("{}", emptied_slice(&text));
        println!("── renumbered open wave ──");
        for w in lock.waves.iter().filter(|w| w.n > 0) {
            println!("wave {} = {:?}", w.n, w.tickets);
        }
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn partial_ship_records_no_emptied_entry() {
        // Disjoint owns → ONE wave holding both tickets. Shipping only half of it must leave
        // no trace: an open wave records nothing until its WHOLE set has landed.
        let dir = scratch_git(
            "emptied-partial",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["b.rs"], &[], "queued")),
            ],
            &["wave 41 CLOSED — test ledger"],
        );
        let before = repack_quiet(&dir).unwrap();
        assert_eq!(
            before.tickets_in_wave(42),
            vec!["T-1".to_string(), "T-2".to_string()]
        );
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["a.rs"], &[], "shipped"),
        )
        .unwrap();
        let lock = repack_quiet(&dir).unwrap();
        assert!(
            lock.emptied.is_empty(),
            "partial ship froze a wave: {lock:?}"
        );
        assert_eq!(lock.tickets_in_wave(42), vec!["T-2".to_string()]);
        assert!(check_as_errors(&dir).is_empty());
        let text = fs::read_to_string(lock_path(&dir)).unwrap();
        assert!(
            !text.contains("emptied"),
            "the empty section renders NOTHING: {text}"
        );
        println!(
            "── grep emptied on the partial-ship lock ── {} match(es)",
            text.matches("emptied").count()
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn two_emptied_waves_pend_ascending_and_open_waves_number_past_both() {
        // Three colliding tickets → waves 42/43/44 over base 41. Ship 42's whole set, repack;
        // ship 43's whole set, repack: two pending entries, ascending, and the surviving open
        // wave keeps numbering past the HIGHEST pending label.
        let dir = scratch_git(
            "emptied-two",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["a.rs"], &[], "queued")),
                ("T-3.toml", &work("T-3", 30, &["a.rs"], &[], "queued")),
            ],
            &["wave 41 CLOSED — test ledger"],
        );
        let first = repack_quiet(&dir).unwrap();
        assert_eq!(first.tickets_in_wave(42), vec!["T-1".to_string()]);
        assert_eq!(first.tickets_in_wave(44), vec!["T-3".to_string()]);

        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["a.rs"], &[], "shipped"),
        )
        .unwrap();
        let mid = repack_quiet(&dir).unwrap();
        assert_eq!(mid.emptied.len(), 1);
        assert_eq!(mid.emptied[0].n, 42);

        fs::write(
            dir.join(".ai/tickets/T-2.toml"),
            work("T-2", 20, &["a.rs"], &[], "shipped"),
        )
        .unwrap();
        let lock = repack_quiet(&dir).unwrap();
        let pending: Vec<(u32, Vec<String>)> = lock
            .emptied
            .iter()
            .map(|e| (e.n, e.tickets.clone()))
            .collect();
        assert_eq!(
            pending,
            vec![(42, vec!["T-1".to_string()]), (43, vec!["T-2".to_string()]),],
            "entries pend ascending with their frozen sets: {lock:?}"
        );
        let open: Vec<u32> = lock.waves.iter().filter(|w| w.n > 0).map(|w| w.n).collect();
        assert_eq!(open, vec![44], "numbering starts past pending 43: {lock:?}");
        assert_eq!(lock.tickets_in_wave(44), vec!["T-3".to_string()]);
        assert!(check_as_errors(&dir).is_empty());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn pre_t925_lock_without_emptied_parses_and_empty_section_renders_invisible() {
        // Old-lock compat: the serde default reads every pre-T-925 blob, and an EMPTY section
        // must not touch the render at all — `emptied = []` after the `[[waves]]` tables would
        // not even be valid TOML, and the committed lock must repack byte-identically.
        let text = "version = 1\nmax_concurrent = 8\npack_last = []\nwaves = []\n\n[owns]\n\n[depends_on]\n";
        let lock = parse(text).unwrap();
        assert!(lock.emptied.is_empty(), "absent section parses as empty");
        let rendered = render(&lock).unwrap();
        assert!(
            !rendered.contains("emptied"),
            "an empty section renders NOTHING: {rendered}"
        );
        // And a nonempty section round-trips losslessly.
        let mut with = lock.clone();
        with.emptied.push(LockWave {
            n: 7,
            tickets: vec!["T-9".to_string()],
        });
        let r2 = render(&with).unwrap();
        assert!(r2.contains("[[emptied]]"), "{r2}");
        assert_eq!(parse(&r2).unwrap(), with, "render → parse must be lossless");
    }

    #[test]
    fn check_reds_on_a_perturbed_emptied_entry_until_restored() {
        // The recorded single-pending state from the full-ship test, then three hand-edits to
        // the committed section — each red NAMING the entry, each restored to green. The
        // frozen SET is not recomputable from the tree (that is the point of freezing), so
        // the catchable perturbations are the invariant ones: an emptied set, a set pointing
        // at unshipped work, a label the ledger already closed.
        let dir = scratch_git(
            "emptied-perturb",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["a.rs"], &[], "queued")),
            ],
            &["wave 41 CLOSED — test ledger"],
        );
        repack_quiet(&dir).unwrap();
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["a.rs"], &[], "shipped"),
        )
        .unwrap();
        repack_quiet(&dir).unwrap();
        let good = fs::read_to_string(lock_path(&dir)).unwrap();
        assert!(check_as_errors(&dir).is_empty(), "recorded state is green");
        let block = "[[emptied]]\nn = 42\ntickets = [\"T-1\"]";
        assert!(good.contains(block), "fixture block drifted: {good}");

        // (a) drop the ticket from the frozen set → the set empties → red.
        fs::write(
            lock_path(&dir),
            good.replace(block, "[[emptied]]\nn = 42\ntickets = []"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter()
                .any(|e| e.contains("emptied wave 42 lists no tickets")),
            "an emptied-out set must be red: {errs:?}"
        );
        println!("── perturbed (set emptied) ── {}", errs.join(" | "));

        // (b) point the set at an UNSHIPPED ticket → red naming ticket and status.
        fs::write(
            lock_path(&dir),
            good.replace(block, "[[emptied]]\nn = 42\ntickets = [\"T-2\"]"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter()
                .any(|e| e.contains("emptied wave 42 lists T-2 (queued)")),
            "an unshipped member must be red: {errs:?}"
        );
        println!("── perturbed (unshipped member) ── {}", errs.join(" | "));

        // (c) pull the label to the ledger base → red: that marker already landed.
        fs::write(
            lock_path(&dir),
            good.replace(block, "[[emptied]]\nn = 41\ntickets = [\"T-1\"]"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter()
                .any(|e| e.contains("emptied wave 41 is at or below wave_base 41")),
            "a landed label must be red: {errs:?}"
        );

        // Restore the exact recorded bytes → green.
        fs::write(lock_path(&dir), &good).unwrap();
        let errs = check_as_errors(&dir);
        assert!(errs.is_empty(), "restore must be green: {errs:?}");
        println!("── restored ── check green ({} error(s))", errs.len());
        let _ = fs::remove_dir_all(&dir);
    }
}
