//! T-912.2 — `.ai/tickets/wave.lock`: the compiled wave plan.
//!
//! Tickets are the only source of `owns` / `depends_on` / `pack_last` (T-912.1). This module
//! COMPILES them into one committed TOML lock — `cargo xtask wave repack` is the ONLY legal
//! writer — and `cargo xtask wave check` recomputes and structurally compares. The two hand-kept
//! wave-plan TSVs died in the same commit as the first lock; the migration arm that read them
//! lives in [`crate::wave::legacy_plan`], the one file allowed to name them.
//!
//! ── LOCK SHAPE (pinned emit order; deterministic byte-for-byte) ──────────────────────────────
//!
//! ```toml
//! # auto-generated by cargo xtask wave repack — do not hand-edit
//! version = 1
//! max_concurrent = 8          # TBD_MAX_CONCURRENT at repack time, recorded
//! pack_last = ["T-290"]
//! [[waves]]                    # n = 0 is the parking lot; n >= 1 is the dispatch order
//! n = 0
//! tickets = [...]
//! [owns]                       # per-ticket snapshots, sorted maps
//! [depends_on]
//! ```
//!
//! `pack_last` precedes `[[waves]]` because TOML forbids a root-level value after a table —
//! that constraint, not taste, pins the order.
//!
//! ── WAVE 0 ───────────────────────────────────────────────────────────────────────────────────
//!
//! Wave 0 is the frozen ledger of everything undispatchable: the previous lock's wave 0, plus
//! every ticket whose status is shipped/cancelled/deferred or whose executor is not claude-code.
//! It subsumes the old generation-floor env knob — landed generations live here, so waves 1+
//! are open work only and `current_wave` is simply the first wave n>0 holding an unshipped id.
//! A ticket that becomes dispatchable again (a reopened deferral) LEAVES wave 0 — it is open,
//! so it must pack. Order edits never move wave 0: membership keys off status/executor only.
//! Idea-status claude-code tickets are in neither wave 0 nor waves 1+ — same limbo the TSV gave
//! unfiled tickets — and the `slice-collisions` unplanned warning names the dispatchable ones.
//!
//! ── PACKING (waves 1+) ───────────────────────────────────────────────────────────────────────
//!
//! The live greedy, unchanged from `slice-collisions --repack` (T-620): file-disjoint `owns`
//! per wave (prefix containment collides), `depends_on` forces a dependent strictly later than
//! its dependency's wave, `pack_last` tickets trail in singleton waves, cap `TBD_MAX_CONCURRENT`
//! default 8. Candidates sort by ticket `order`, tie-broken by id — filesystem order is
//! FORBIDDEN as a sort key (the id tie-break is what makes equal-order children deterministic).
//!
//! A dependency edge gates packing ONLY when its target is itself a dispatchable candidate.
//! A target that is shipped/cancelled is satisfied history; a target that is idea/deferred or
//! executor-gated can never pack, and letting it block would deadlock the whole queue on one
//! edge (live case at cutover: T-212 → T-257, status idea). Those edges are WARNED about at
//! repack, never silently honoured and never silently dropped.
//!
//! ── CHECK ────────────────────────────────────────────────────────────────────────────────────
//!
//! `wave check` recomputes wave 0 (baseline = the committed lock's wave 0) and every snapshot
//! from the ticket files, structurally compares against the committed lock, and validates the
//! committed waves 1+: exactly-dispatchable membership, no duplicates, per-wave owns
//! disjointness, cap, pack_last trailing. A MISSING lock is a DidNotRun refusal — exit nonzero,
//! never an empty-plan success (the `plan_rows` `unwrap_or_default` false-green class this
//! program exists to kill).
//!
//! Waves 1+ GROUPING is the packer's recorded choice and is validated, not re-derived: the
//! migration lock froze the committed TSV groups verbatim (T-912.2 must-ship 3), and that
//! grouping predates T-912.1's merged dependency edges — it holds one known inversion (T-212 in
//! an earlier wave than its dependency T-685). The packer enforces dependency order at every
//! later repack; check enforcing it retroactively would refuse the migration lock itself.
//! Same reason check borrows the lock's recorded `max_concurrent` instead of the ambient env:
//! the lock is self-describing, and a different shell must not turn a committed plan red.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use tbd_tickets::{StatusName, Ticket, parse_ticket_toml};

pub const LOCK_REL: &str = ".ai/tickets/wave.lock";
pub const LOCK_VERSION: u32 = 1;
const HEADER: &str = "# auto-generated by cargo xtask wave repack — do not hand-edit\n";

pub fn lock_path(root: &Path) -> PathBuf {
    root.join(LOCK_REL)
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct LockWave {
    pub n: u32,
    pub tickets: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct WaveLock {
    pub version: u32,
    pub max_concurrent: usize,
    pub pack_last: Vec<String>,
    pub waves: Vec<LockWave>,
    pub owns: BTreeMap<String, Vec<String>>,
    pub depends_on: BTreeMap<String, Vec<String>>,
}

impl WaveLock {
    pub fn tickets_in_wave(&self, n: u32) -> Vec<String> {
        self.waves
            .iter()
            .find(|w| w.n == n)
            .map(|w| w.tickets.clone())
            .unwrap_or_default()
    }

    pub fn open_ids(&self) -> Vec<String> {
        self.waves
            .iter()
            .filter(|w| w.n > 0)
            .flat_map(|w| w.tickets.iter().cloned())
            .collect()
    }
}

/// The per-ticket facts the compiler needs, from EVERY `.ai/tickets/T-*.toml` — children
/// included. NOT the parents-only registry loader; a child id like T-090.4 must be a candidate.
#[derive(Debug, Clone)]
pub struct TicketView {
    pub id: String,
    pub title: String,
    pub work: bool,
    pub status: StatusName,
    pub order: Option<i64>,
    pub executor: Option<String>,
    pub owns: Vec<String>,
    pub depends_on: Vec<String>,
    pub pack_last: bool,
}

impl TicketView {
    /// Can a slice agent take this ticket? Work + live status + claude-code executor
    /// (absent executor defaults to claude-code, as everywhere else in the pipeline).
    pub fn dispatchable(&self) -> bool {
        self.work
            && self.status.is_live()
            && self.executor.as_deref().unwrap_or("claude-code") == "claude-code"
    }

    /// Belongs in wave 0: landed or never agent-actionable. The status list mirrors the old
    /// registry `dispatchable()` refusals (the typed schema has no `blocked`); a non-claude-code
    /// executor is operator work by the D5 gate regardless of status.
    pub fn parked(&self) -> bool {
        matches!(
            self.status,
            StatusName::Shipped | StatusName::Cancelled | StatusName::Deferred
        ) || self
            .executor
            .as_deref()
            .map(|e| e != "claude-code")
            .unwrap_or(false)
    }
}

pub fn load_views(root: &Path) -> Result<Vec<TicketView>> {
    let dir = crate::tickets_store::tickets_dir(root);
    let mut views = Vec::new();
    for ent in std::fs::read_dir(&dir).with_context(|| dir.display().to_string())? {
        let ent = ent?;
        let name = ent.file_name();
        let name = name.to_string_lossy();
        if !name.starts_with("T-") || !name.ends_with(".toml") {
            continue;
        }
        let text = std::fs::read_to_string(ent.path())?;
        let t = parse_ticket_toml(&text)
            .map_err(|e| anyhow::anyhow!("{}: {e}", ent.path().display()))?;
        let v = match t {
            Ticket::Program(p) => TicketView {
                id: p.id,
                title: p.title,
                work: false,
                status: p.status.name(),
                order: p.status.order(),
                executor: p.executor,
                owns: p.owns,
                depends_on: p.depends_on,
                pack_last: p.pack_last == Some(true),
            },
            Ticket::Work(w) => TicketView {
                id: w.id,
                title: w.title,
                work: true,
                status: w.status.name(),
                order: w.status.order(),
                executor: w.executor,
                owns: w.owns,
                depends_on: w.depends_on,
                pack_last: w.pack_last == Some(true),
            },
        };
        views.push(v);
    }
    // Sorted for stable iteration in diagnostics. NEVER used as a packing sort key — candidates
    // sort by (order, id) below, and glob order is forbidden by the program spec.
    views.sort_by(|a, b| a.id.cmp(&b.id));
    Ok(views)
}

pub fn max_concurrent() -> usize {
    std::env::var("TBD_MAX_CONCURRENT")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(8)
}

/// Two owns sets collide when any path pair is equal or one prefix-contains the other —
/// byte-for-byte the `slice-collisions` rule.
pub fn collides(a: &[String], b: &[String]) -> bool {
    for x in a {
        for y in b {
            if x == y
                || x.starts_with(&format!("{}/", y.trim_end_matches('/')))
                || y.starts_with(&format!("{}/", x.trim_end_matches('/')))
            {
                return true;
            }
        }
    }
    false
}

/// Corpus-wide snapshots: every nonempty `owns` / `depends_on`, every `pack_last = true`.
/// Corpus-wide (not lock-member-scoped) so the writer and the checker cannot disagree about
/// which tickets are in scope.
type Snapshots = (
    BTreeMap<String, Vec<String>>,
    BTreeMap<String, Vec<String>>,
    Vec<String>,
);

fn snapshots(views: &[TicketView]) -> Snapshots {
    let mut owns = BTreeMap::new();
    let mut deps = BTreeMap::new();
    let mut last = Vec::new();
    for v in views {
        if !v.owns.is_empty() {
            owns.insert(v.id.clone(), v.owns.clone());
        }
        if !v.depends_on.is_empty() {
            deps.insert(v.id.clone(), v.depends_on.clone());
        }
        if v.pack_last {
            last.push(v.id.clone());
        }
    }
    last.sort();
    (owns, deps, last)
}

/// Wave 0 = baseline ∪ parked − dispatchable, sorted by id (wave 0 ignores `order`).
///
/// The baseline union is what keeps wave 0 a LEDGER: an id whose ticket file later disappears
/// stays parked instead of silently vanishing from the plan. The dispatchable subtraction is
/// the one legal exit — a reopened ticket is open work and must pack, and listing it in both
/// halves would make the lock disagree with itself.
fn wave_zero(views: &[TicketView], baseline: &BTreeSet<String>) -> Vec<String> {
    let mut set: BTreeSet<String> = baseline.clone();
    for v in views {
        if v.parked() {
            set.insert(v.id.clone());
        }
    }
    for v in views {
        if v.dispatchable() {
            set.remove(&v.id);
        }
    }
    set.into_iter().collect()
}

/// The live greedy over dispatchable candidates sorted by (`order`, id).
///
/// Returns the packed waves (1..N by position). Dependency edges whose target cannot ever pack
/// (not dispatchable, not shipped/cancelled) are collected into `warnings` and do not gate —
/// see the module header for the T-212 → T-257 case that forces this.
fn greedy_waves(
    views: &[TicketView],
    cap: usize,
    warnings: &mut Vec<String>,
) -> Result<Vec<Vec<String>>> {
    let by_id: BTreeMap<&str, &TicketView> = views.iter().map(|v| (v.id.as_str(), v)).collect();
    let mut cands: Vec<&TicketView> = views.iter().filter(|v| v.dispatchable()).collect();
    cands.sort_by(|a, b| {
        a.order
            .unwrap_or(i64::MAX)
            .cmp(&b.order.unwrap_or(i64::MAX))
            .then_with(|| a.id.cmp(&b.id))
    });
    let disp_ids: HashSet<&str> = cands.iter().map(|v| v.id.as_str()).collect();

    for c in &cands {
        for d in &c.depends_on {
            if disp_ids.contains(d.as_str()) {
                continue; // schedulable — the packer orders around it
            }
            let landed = by_id
                .get(d.as_str())
                .map(|t| matches!(t.status, StatusName::Shipped | StatusName::Cancelled))
                .unwrap_or(false);
            if !landed {
                let what = by_id
                    .get(d.as_str())
                    .map(|t| t.status.as_str())
                    .unwrap_or("no ticket file");
                warnings.push(format!(
                    "{} depends_on {d} ({what}) — target can never pack, edge does not gate",
                    c.id
                ));
            }
        }
    }

    let last: Vec<&TicketView> = cands.iter().copied().filter(|v| v.pack_last).collect();
    let mut remaining: Vec<&TicketView> = cands.iter().copied().filter(|v| !v.pack_last).collect();
    // An edge blocks while its target is a dispatchable candidate not yet packed in an EARLIER
    // wave — `packed` updates between waves, so same-wave dependency is impossible.
    let mut packed: HashSet<String> = HashSet::new();
    let blocked = |v: &TicketView, packed: &HashSet<String>| {
        v.depends_on
            .iter()
            .any(|d| disp_ids.contains(d.as_str()) && !packed.contains(d))
    };

    let mut waves: Vec<Vec<String>> = Vec::new();
    while !remaining.is_empty() {
        let mut wave: Vec<String> = Vec::new();
        let mut used: Vec<&[String]> = Vec::new();
        for c in &remaining {
            if blocked(c, &packed) {
                continue;
            }
            if used.iter().any(|u| collides(&c.owns, u)) {
                continue;
            }
            wave.push(c.id.clone());
            used.push(&c.owns);
            if wave.len() >= cap {
                break;
            }
        }
        if wave.is_empty() {
            // Everything left is dep-blocked with nothing packable underneath: a cycle in the
            // dispatchable graph. That is a bug worth shouting about, exactly as the TSV-era
            // repack did.
            let free: Vec<&TicketView> = remaining
                .iter()
                .copied()
                .filter(|v| !blocked(v, &packed))
                .collect();
            if free.is_empty() {
                let ids: Vec<&str> = remaining.iter().take(8).map(|v| v.id.as_str()).collect();
                bail!("depends_on deadlock: {ids:?} — check those tickets' depends_on edges");
            }
            wave.push(free[0].id.clone());
        }
        let picked: HashSet<&str> = wave.iter().map(String::as_str).collect();
        remaining.retain(|v| !picked.contains(v.id.as_str()));
        for id in &wave {
            packed.insert(id.clone());
        }
        waves.push(wave);
    }
    // pack_last tickets trail, one singleton wave each, in candidate order.
    for v in last {
        packed.insert(v.id.clone());
        waves.push(vec![v.id.clone()]);
    }
    Ok(waves)
}

fn assemble(
    views: &[TicketView],
    baseline: &BTreeSet<String>,
    open_waves: Vec<Vec<String>>,
    cap: usize,
) -> WaveLock {
    let (owns, depends_on, pack_last) = snapshots(views);
    let mut waves = Vec::new();
    let zero = wave_zero(views, baseline);
    if !zero.is_empty() {
        waves.push(LockWave {
            n: 0,
            tickets: zero,
        });
    }
    for (i, tickets) in open_waves.into_iter().enumerate() {
        waves.push(LockWave {
            n: (i + 1) as u32,
            tickets,
        });
    }
    WaveLock {
        version: LOCK_VERSION,
        max_concurrent: cap,
        pack_last,
        waves,
        owns,
        depends_on,
    }
}

/// Compile the lock from the ticket tree: wave 0 on `baseline`, waves 1+ from the greedy.
pub fn compile(root: &Path, baseline: &BTreeSet<String>) -> Result<WaveLock> {
    let views = load_views(root)?;
    let mut warnings = Vec::new();
    let cap = max_concurrent();
    let open = greedy_waves(&views, cap, &mut warnings)?;
    for w in &warnings {
        eprintln!("wave repack: warning: {w}");
    }
    Ok(assemble(&views, baseline, open, cap))
}

pub fn render(lock: &WaveLock) -> Result<String> {
    let body = toml::to_string(lock).context("render wave.lock")?;
    let mut out = String::with_capacity(HEADER.len() + body.len());
    out.push_str(HEADER);
    out.push_str(&body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

pub fn parse(text: &str) -> Result<WaveLock> {
    toml::from_str(text).context("parse wave.lock (TOML)")
}

/// The DidNotRun refusal every reader shares: an absent lock is a refusal, never an empty plan.
pub fn missing_lock_error(root: &Path) -> String {
    format!(
        "{} missing — DidNotRun: run `cargo xtask wave repack`. A missing lock is a refusal, never an empty plan.",
        lock_path(root).display()
    )
}

pub fn load(root: &Path) -> Result<WaveLock> {
    let p = lock_path(root);
    if !p.is_file() {
        bail!("{}", missing_lock_error(root));
    }
    let text = std::fs::read_to_string(&p).with_context(|| p.display().to_string())?;
    parse(&text)
}

pub fn write(root: &Path, lock: &WaveLock) -> Result<()> {
    let p = lock_path(root);
    std::fs::write(&p, render(lock)?).with_context(|| p.display().to_string())?;
    Ok(())
}

/// Refresh the lock after a registry status write (the `ticket ship` / `ticket set-status`
/// bookkeeping hook, and `platform wave land`'s final step). Same writer as `wave repack`;
/// wave 0 baseline carries over from the previous lock when one exists.
pub fn repack_quiet(root: &Path) -> Result<WaveLock> {
    if crate::wave::legacy_plan::any_tsv_present(root) {
        return migrate_from_tsv(root);
    }
    let baseline: BTreeSet<String> = match load(root) {
        Ok(prev) => prev.tickets_in_wave(0).into_iter().collect(),
        Err(_) => BTreeSet::new(), // first-ever compile on a lockless tree
    };
    let lock = compile(root, &baseline)?;
    write(root, &lock)?;
    Ok(lock)
}

/// One-shot cutover: waves 1+ are the committed TSV open-id groups (platform then mod, label
/// groups in file order, relabeled 1..N), wave 0 is every non-dispatchable TSV id plus every
/// parked ticket. Deletes both TSVs — the lock and the deletion ride the same commit.
fn migrate_from_tsv(root: &Path) -> Result<WaveLock> {
    let views = load_views(root)?;
    let by_id: BTreeMap<&str, &TicketView> = views.iter().map(|v| (v.id.as_str(), v)).collect();
    let rows = crate::wave::legacy_plan::working_tree_rows(root)?;

    let mut label_order: Vec<&str> = Vec::new();
    let mut groups: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    let mut wave0_tsv: BTreeSet<String> = BTreeSet::new();
    for (label, id) in &rows {
        let disp = by_id.get(id.as_str()).map(|v| v.dispatchable()) == Some(true);
        if disp {
            if !groups.contains_key(label.as_str()) {
                label_order.push(label.as_str());
            }
            groups.entry(label.as_str()).or_default().push(id.as_str());
        } else {
            wave0_tsv.insert(id.clone());
        }
    }
    let open: Vec<Vec<String>> = label_order
        .iter()
        .map(|l| groups[l].iter().map(|s| s.to_string()).collect())
        .collect();

    let lock = assemble(&views, &wave0_tsv, open, max_concurrent());
    write(root, &lock)?;
    crate::wave::legacy_plan::delete_tsvs(root)?;
    Ok(lock)
}

fn summary(lock: &WaveLock) -> String {
    let open: usize = lock
        .waves
        .iter()
        .filter(|w| w.n > 0)
        .map(|w| w.tickets.len())
        .sum();
    let n_open = lock.waves.iter().filter(|w| w.n > 0).count();
    let parked = lock
        .waves
        .iter()
        .find(|w| w.n == 0)
        .map(|w| w.tickets.len())
        .unwrap_or(0);
    format!("{open} open ticket(s) in {n_open} wave(s), {parked} parked at wave 0")
}

pub fn cmd_repack(root: &Path) -> Result<u8> {
    let migrated = crate::wave::legacy_plan::any_tsv_present(root);
    let lock = repack_quiet(root)?;
    if migrated {
        println!("wave.lock: migrated from the committed wave-plan TSVs (both deleted)");
    }
    println!("wrote {}: {}", LOCK_REL, summary(&lock));
    Ok(0)
}

/// All check findings as error strings — embedded verbatim into `ticket check`.
pub fn check_as_errors(root: &Path) -> Vec<String> {
    let lock = match load(root) {
        Ok(l) => l,
        Err(e) => return vec![format!("{e:#}")],
    };
    let views = match load_views(root) {
        Ok(v) => v,
        Err(e) => return vec![format!("wave check: {e:#}")],
    };
    let mut errors = Vec::new();

    if lock.version != LOCK_VERSION {
        errors.push(format!(
            "wave.lock version {} != {LOCK_VERSION} — regenerate with `cargo xtask wave repack`",
            lock.version
        ));
    }

    // Wave numbering: strictly increasing, wave 0 first when present, no duplicate n.
    let ns: Vec<u32> = lock.waves.iter().map(|w| w.n).collect();
    let mut sorted = ns.clone();
    sorted.sort_unstable();
    sorted.dedup();
    if ns != sorted {
        errors.push(format!(
            "wave.lock wave numbers are not strictly increasing: {ns:?}"
        ));
    }

    // Wave 0 recompute against the committed lock's own baseline.
    let baseline: BTreeSet<String> = lock.tickets_in_wave(0).into_iter().collect();
    let expect_zero = wave_zero(&views, &baseline);
    let got_zero = lock.tickets_in_wave(0);
    if expect_zero != got_zero {
        let exp: BTreeSet<&String> = expect_zero.iter().collect();
        let got: BTreeSet<&String> = got_zero.iter().collect();
        let missing: Vec<&&String> = exp.difference(&got).take(10).collect();
        let extra: Vec<&&String> = got.difference(&exp).take(10).collect();
        errors.push(format!(
            "wave.lock wave 0 is stale — missing {missing:?}, extra {extra:?}: run `cargo xtask wave repack`"
        ));
    }

    // Snapshots must equal the tickets, corpus-wide.
    let (owns, deps, last) = snapshots(&views);
    for (name, want, got) in [
        ("owns", &owns, &lock.owns),
        ("depends_on", &deps, &lock.depends_on),
    ] {
        if want != got {
            let mut diffs: Vec<String> = Vec::new();
            for (k, v) in want {
                if got.get(k) != Some(v) {
                    diffs.push(k.clone());
                }
            }
            for k in got.keys() {
                if !want.contains_key(k) {
                    diffs.push(k.clone());
                }
            }
            diffs.sort();
            diffs.dedup();
            diffs.truncate(10);
            errors.push(format!(
                "wave.lock {name} snapshot disagrees with the ticket files on {diffs:?} — run `cargo xtask wave repack`"
            ));
        }
    }
    if last != lock.pack_last {
        errors.push(format!(
            "wave.lock pack_last {:?} disagrees with the ticket files {:?} — run `cargo xtask wave repack`",
            lock.pack_last, last
        ));
    }

    // Waves 1+: every id dispatchable today, no id listed twice anywhere, per-wave owns
    // disjoint, cap respected, pack_last trailing as singletons. Grouping itself is the
    // packer's recorded choice — see the module header for why dependency order is enforced
    // at repack, not here.
    let by_id: BTreeMap<&str, &TicketView> = views.iter().map(|v| (v.id.as_str(), v)).collect();
    let mut seen: HashSet<&str> = got_zero.iter().map(String::as_str).collect();
    let mut past_pack_last = false;
    for w in lock.waves.iter().filter(|w| w.n > 0) {
        if w.tickets.is_empty() {
            errors.push(format!("wave.lock wave {} is empty", w.n));
        }
        if w.tickets.len() > lock.max_concurrent {
            errors.push(format!(
                "wave.lock wave {} holds {} tickets over the recorded cap {}",
                w.n,
                w.tickets.len(),
                lock.max_concurrent
            ));
        }
        let is_last_wave = w.tickets.iter().any(|t| lock.pack_last.contains(t));
        if is_last_wave && w.tickets.len() > 1 {
            errors.push(format!(
                "wave.lock wave {} mixes pack_last with other tickets",
                w.n
            ));
        }
        if past_pack_last && !is_last_wave {
            errors.push(format!(
                "wave.lock wave {} follows a pack_last wave but is not one — pack_last tickets trail",
                w.n
            ));
        }
        past_pack_last |= is_last_wave;
        for t in &w.tickets {
            if !seen.insert(t.as_str()) {
                errors.push(format!("wave.lock lists {t} more than once"));
            }
            match by_id.get(t.as_str()) {
                None => errors.push(format!(
                    "wave.lock wave {} lists {t}, which has no ticket file — run `cargo xtask wave repack`",
                    w.n
                )),
                Some(v) if !v.dispatchable() => errors.push(format!(
                    "wave.lock wave {} lists {t} ({}, executor {}) — not dispatchable; run `cargo xtask wave repack`",
                    w.n,
                    v.status.as_str(),
                    v.executor.as_deref().unwrap_or("claude-code"),
                )),
                Some(_) => {}
            }
        }
        for i in 0..w.tickets.len() {
            for j in (i + 1)..w.tickets.len() {
                let a = by_id.get(w.tickets[i].as_str()).map(|v| v.owns.as_slice());
                let b = by_id.get(w.tickets[j].as_str()).map(|v| v.owns.as_slice());
                if let (Some(a), Some(b)) = (a, b) {
                    if collides(a, b) {
                        errors.push(format!(
                            "wave.lock wave {}: {} and {} own overlapping paths — never the same wave",
                            w.n, w.tickets[i], w.tickets[j]
                        ));
                    }
                }
            }
        }
    }

    errors
}

pub fn cmd_check(root: &Path) -> Result<u8> {
    let errors = check_as_errors(root);
    if !errors.is_empty() {
        for e in &errors {
            eprintln!("ERROR: {e}");
        }
        bail!("wave check failed ({} error(s))", errors.len());
    }
    let lock = load(root)?;
    println!("wave.lock OK: {}", summary(&lock));
    Ok(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn scratch(tag: &str, files: &[(&str, &str)]) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("t912-lock-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        let tickets = dir.join(".ai/tickets");
        fs::create_dir_all(&tickets).unwrap();
        fs::write(tickets.join("ROOT"), "# ticket-registry root marker\n").unwrap();
        for (name, body) in files {
            fs::write(tickets.join(name), body).unwrap();
        }
        dir
    }

    fn work(id: &str, order: i64, owns: &[&str], deps: &[&str], status: &str) -> String {
        let owns = owns
            .iter()
            .map(|o| format!("\"{o}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let deps = deps
            .iter()
            .map(|d| format!("\"{d}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "id = \"{id}\"\nkind = \"work\"\ntitle = \"t {id}\"\nsummary = \"s\"\nstatus = \"{status}\"\norder = {order}\ndepends_on = [{deps}]\nowns = [{owns}]\n\n[scope.repo]\nlayers = [\"xtask\"]\n"
        )
    }

    #[test]
    fn overlapping_owns_never_share_a_wave() {
        let dir = scratch(
            "overlap",
            &[
                (
                    "T-1.toml",
                    &work("T-1", 10, &["crates/foo/a.rs"], &[], "queued"),
                ),
                (
                    "T-2.toml",
                    &work("T-2", 20, &["crates/foo/a.rs"], &[], "queued"),
                ),
            ],
        );
        let lock = compile(&dir, &BTreeSet::new()).unwrap();
        let open: Vec<&LockWave> = lock.waves.iter().filter(|w| w.n > 0).collect();
        assert_eq!(open.len(), 2, "colliding owns must split: {lock:?}");
        assert_eq!(open[0].tickets, vec!["T-1".to_string()]);
        assert_eq!(open[1].tickets, vec!["T-2".to_string()]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn dependent_packs_strictly_after_unshipped_dependency() {
        // T-2 has the LOWER order but depends on T-9 — it must still land strictly later.
        let dir = scratch(
            "deps",
            &[
                ("T-2.toml", &work("T-2", 10, &["a.rs"], &["T-9"], "queued")),
                ("T-9.toml", &work("T-9", 20, &["b.rs"], &[], "queued")),
            ],
        );
        let lock = compile(&dir, &BTreeSet::new()).unwrap();
        let wave_of = |id: &str| {
            lock.waves
                .iter()
                .find(|w| w.tickets.iter().any(|t| t == id))
                .map(|w| w.n)
                .unwrap()
        };
        assert!(
            wave_of("T-2") > wave_of("T-9"),
            "dependent same-or-earlier than dependency: {lock:?}"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn candidates_sort_by_order_then_id_never_glob_order() {
        // File names sort T-10 < T-9 lexically; order says T-9 first.
        let dir = scratch(
            "order",
            &[
                ("T-10.toml", &work("T-10", 20, &["a.rs"], &[], "queued")),
                ("T-9.toml", &work("T-9", 10, &["b.rs"], &[], "queued")),
                ("T-8.toml", &work("T-8", 20, &["c.rs"], &[], "queued")),
            ],
        );
        let lock = compile(&dir, &BTreeSet::new()).unwrap();
        // One wave (disjoint, under cap) — candidate order is (order, id): T-9, T-10, T-8→ tie
        // on 20 broken by id: "T-10" < "T-8" lexicographically.
        assert_eq!(
            lock.tickets_in_wave(1),
            vec!["T-9".to_string(), "T-10".to_string(), "T-8".to_string()]
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn compile_render_is_deterministic_and_roundtrips() {
        let dir = scratch(
            "det",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["b/dir"], &["T-1"], "queued")),
                ("T-3.toml", &work("T-3", 30, &["c.rs"], &[], "shipped")),
            ],
        );
        let a = compile(&dir, &BTreeSet::new()).unwrap();
        let b = compile(&dir, &BTreeSet::new()).unwrap();
        assert_eq!(a, b);
        let ra = render(&a).unwrap();
        assert_eq!(
            ra,
            render(&b).unwrap(),
            "double compile must render identical bytes"
        );
        assert!(ra.starts_with(HEADER));
        assert!(ra.ends_with('\n'));
        let parsed = parse(&ra).unwrap();
        assert_eq!(parsed, a, "render → parse must be lossless");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn wave_zero_is_baseline_union_parked_minus_reopened() {
        let dir = scratch(
            "zero",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["b.rs"], &[], "shipped")),
            ],
        );
        let baseline: BTreeSet<String> = ["T-1".to_string(), "T-777".to_string()]
            .into_iter()
            .collect();
        let views = load_views(&dir).unwrap();
        // T-1 reopened → leaves wave 0; T-777 has no file → ledger keeps it; T-2 parked.
        assert_eq!(
            wave_zero(&views, &baseline),
            vec!["T-2".to_string(), "T-777".to_string()]
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn missing_lock_is_a_did_not_run_refusal() {
        let dir = scratch("missing", &[]);
        let err = format!("{:#}", load(&dir).unwrap_err());
        assert!(
            err.contains("DidNotRun"),
            "want DidNotRun refusal, got: {err}"
        );
        assert!(err.contains("never an empty plan"), "got: {err}");
        let errs = check_as_errors(&dir);
        assert_eq!(errs.len(), 1);
        assert!(errs[0].contains("DidNotRun"));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn check_reds_on_perturbed_owns_and_edges_and_stale_membership() {
        let dir = scratch(
            "perturb",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["b.rs"], &["T-1"], "queued")),
            ],
        );
        let lock = compile(&dir, &BTreeSet::new()).unwrap();
        write(&dir, &lock).unwrap();
        assert!(check_as_errors(&dir).is_empty(), "fresh lock must be green");

        // Perturb owns without repack → red.
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["zzz.rs"], &[], "queued"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter().any(|e| e.contains("owns snapshot")),
            "owns perturbation must be red: {errs:?}"
        );
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["a.rs"], &[], "queued"),
        )
        .unwrap();
        assert!(check_as_errors(&dir).is_empty(), "restore must be green");

        // Remove a depends_on edge without repack → red.
        fs::write(
            dir.join(".ai/tickets/T-2.toml"),
            work("T-2", 20, &["b.rs"], &[], "queued"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter().any(|e| e.contains("depends_on snapshot")),
            "edge removal must be red: {errs:?}"
        );
        fs::write(
            dir.join(".ai/tickets/T-2.toml"),
            work("T-2", 20, &["b.rs"], &["T-1"], "queued"),
        )
        .unwrap();
        assert!(check_as_errors(&dir).is_empty());

        // Ship without repack → membership + wave 0 red.
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 10, &["a.rs"], &[], "shipped"),
        )
        .unwrap();
        let errs = check_as_errors(&dir);
        assert!(
            errs.iter().any(|e| e.contains("wave 0 is stale")),
            "ship without repack must red wave 0: {errs:?}"
        );
        assert!(
            errs.iter().any(|e| e.contains("not dispatchable")),
            "shipped id left in an open wave must be red: {errs:?}"
        );
        // Repack (the ship hook path) → green again, id parked.
        let lock = repack_quiet(&dir).unwrap();
        assert!(check_as_errors(&dir).is_empty());
        assert!(lock.tickets_in_wave(0).contains(&"T-1".to_string()));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn reorder_changes_open_waves_only_never_wave_zero() {
        let dir = scratch(
            "reorder",
            &[
                ("T-1.toml", &work("T-1", 10, &["a.rs"], &[], "queued")),
                ("T-2.toml", &work("T-2", 20, &["a.rs"], &[], "queued")),
                ("T-3.toml", &work("T-3", 30, &["c.rs"], &[], "shipped")),
            ],
        );
        let before = repack_quiet(&dir).unwrap();
        assert_eq!(before.tickets_in_wave(1), vec!["T-1".to_string()]);
        // Swap the two open orders.
        fs::write(
            dir.join(".ai/tickets/T-1.toml"),
            work("T-1", 40, &["a.rs"], &[], "queued"),
        )
        .unwrap();
        let after = repack_quiet(&dir).unwrap();
        assert_eq!(after.tickets_in_wave(1), vec!["T-2".to_string()]);
        assert_eq!(
            before.tickets_in_wave(0),
            after.tickets_in_wave(0),
            "order edits must never move wave 0"
        );
        let _ = fs::remove_dir_all(&dir);
    }
}
