//! Role: live operation source for structural regression checks.
//! Position: frontend test support for the `mission_document` and `mission_operations` boundary.
//! Signals & state: compile-time source text only.
//! Invariants: include each production shard once and keep domain and adapter sources distinct.

/// The live entity operation surface: the frontend shards that carry host state — the armed
/// placement and the entity selection — and the map-engine hosted commands the rest of them
/// became.
pub(crate) const ENTITY: &str = concat!(
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/armed_placement/mod.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/armed_placement/palette_arming.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/armed_placement/map_release.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/armed_placement/zone_draw.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/entity_selection.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/document_edit.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/document_search.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/entity_clipboard.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/orbat_roster.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/placed_vehicles.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/entity_connections.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/map_markers.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/zone_authoring.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/map_comments.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/editor_layers.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../legacy/map_engine/src/editing/hosted_commands/map_triggers.rs"
    )),
    "\n",
);

/// The installed editor context: the handles and signals the editor's panels reach the open
/// mission through, and the document reads and writes that go through them.
pub(crate) const CONTEXT: &str = concat!(
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/editor_context/mod.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/editor_context/installation.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/editor_context/document_fields.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/editor_context/attributes_modal.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/workspaces/editor/bridge/host_state/editor_context/dock_mirrors.rs"
    )),
    "\n",
);

/// Mission document operations source.
pub(crate) const DOMAIN_ENTITY: &str = concat!(
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/mod.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/selection.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/identity.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/comments.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/connections.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/roster.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/vehicles.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/markers.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/zones.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/clipboard.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/placement.rs"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../crates/mission/mission_operations/src/entity/factions.rs"
    )),
    "\n",
);
