MenuManager {
 MenuPresets {
  MenuPreset TBD_UIShell {
   Layout "{7BD1A70000000701}UI/layouts/Core/TBD_ScreenShell.layout"
   Class "TBD_ShellScreen"
  }
  MenuPreset TBD_Spectator {
   Layout "{7BD1A70000000701}UI/layouts/Core/TBD_ScreenShell.layout"
   Class "TBD_SpectatorScreen"
  }
  MenuPreset TBD_UIBriefing {
   Layout "{7BD1A70000000D01}UI/layouts/PreGame/Briefing/TBD_BriefingScreen.layout"
   ActionContext "MapContext"
   Class "TBD_BriefingScreen"
  }
  MenuPreset TBD_UILobby {
   Layout "{7BD1A70000000C01}UI/layouts/PreGame/Lobby/TBD_LobbyScreen.layout"
   Class "TBD_LobbyScreen"
  }
  MenuPreset TBD_UIAdmin {
   Layout "{7BD1A70000000701}UI/layouts/Core/TBD_ScreenShell.layout"
   Class "TBD_AdminScreen"
  }
  MenuPreset TBD_UIMissionSelector {
   Layout "{7BD1A70000000B01}UI/layouts/PreGame/MissionSelector/TBD_MissionSelector.layout"
   Class "TBD_MissionSelectorScreen"
  }
 }
}
